### ISSUE TITLE
Synch with dev repos needs work

### ISSUE THREAD

**Issue by Rasbats** [opencpn-manuals/plugins#1]
The basic website is fine but the sources script to align with dev repos needs testing.

[https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html](https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html)

**Comment by Rasbats** [comment]
When I run update this seems to work but when saved in sources.state we get the opencpn-manuals/plugins commit reference.

**Comment by leamas** [comment]
I have this on my list for tomorrow (late CET) or .onday

**Comment by leamas** [comment]
@rasbats: hm... The first step would be to migrate the current sources into this very project. To be precise, so I don't mess it up: Which repository and which branch have you been using to build the current plugins manual at https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html ?

**Comment by Rasbats** [comment]
[https://github.com/opencpn-manuals/plugins](https://github.com/opencpn-manuals/plugins)

Stripped out all the branches other than 'main'. This contains the work from your previous 'manual' branch.

**Comment by leamas** [comment]
Can you please check the status as it right now there? Currently, there is:

  - https://github.com/Rasbats/opencpn-plugins-manual.git/main
  - Some added files, but nothing  changed besides .gitignore.

I have made *no* checks, just shuffling code into our main three repos.

**Comment by Rasbats** [comment]
[https://github.com/Rasbats/opencpn-plugins-manual.git/main](https://github.com/Rasbats/opencpn-plugins-manual.git/main)

?????? This repo was abandoned (needs deleting). All the current work is in:

[https://github.com/opencpn-manuals/plugins](https://github.com/opencpn-manuals/plugins)

This was moved from:

[https://github.com/Rasbats/ocpn-manuals](https://github.com/Rasbats/ocpn-manuals)

I thought the idea was to break out the plugins so that it could be built like this:

[https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html](https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html)

**Comment by leamas** [comment]
Could you check the current contents in    https://github.com/opencpn-manuals/plugins?  The top commit is *ba870bc827- Create .nojekyll* Is this OK?

I was interrupted when working with these things, just want to check that I did not mess it up (in which case we can sort it out, but it might take time :( )

**Comment by leamas** [comment]
OK, I have rebuilt the overall main manual. It's available at https://opencpn-manuals.github.io/main/. Is the plugins manual part sound and safe?

Filing separate issue about checked in files.

**Comment by leamas** [comment]
> The basic website is fine but the sources script to align with dev repos needs testing.

You are talking about source-state.sh, right? If so, I have actually used it now without any errors I can see (besides bad error handling which caused me a looooong loop.)

**Comment by Rasbats** [comment]
Yes, source-state.sh. There is a lot of crud in the base folder but I will remove that idc. It was to help me update the sources.state file.

**Comment by leamas** [comment]
I suggest that we close this one and while keeping the  discussing going in #4. OK?

**Comment by Rasbats** [comment]
Ok.
