### ISSUE TITLE
Link fix progress

### ISSUE THREAD

**Issue by Rasbats** [opencpn-manuals/plugins#11]
=== AIS/adar
https://github.com/opencpn-radar-pi/radar_pi.git  DONE
https://github.com/nohal/aisradar_pi.git          DONE
https://github.com/rgleason/rtlsdr_pi.git    DONE /leamas [PR](https://github.com/rgleason/rtlsdr_pi/pull/5) Merged
=== Charts
https://github.com/bdbcat/nvc_pi.git    WONTFIX?
https://github.com/bdbcat/s63_pi.git   DONE
https://github.com/bdbcat/bsb4_pi.git  WONTFIX?
https://github.com/bdbcat/oeSENC_pi.git    DONE. See #13 and #10
https://github.com/bdbcat/ofc_pi.git  WONTFIX?
https://github.com/Rasbats/photolayer_pi.git    DONE Broken link but is this a problem in opentopomap? filed an [issue](https://github.com/Rasbats/photolayer_pi/issues/36)
https://github.com/Rasbats/vfkaps_pi.git      DONE
https://github.com/rgleason/rotationctrl_pi.git   DONE /leamas [PR](https://github.com/rgleason/rotationctrl_pi/pull/2) Merged
https://github.com/rgleason/chartscale_pi.git   DONE 
https://github.com/nohal/objsearch_pi.git  DONE
https://github.com/rgleason/projections_pi.git   DONE /leamas [PR](https://github.com/rgleason/projections_pi/pull/3) Merged

=== Logs
https://github.com/rgleason/dashboard_tactics_pi.git
https://github.com/rgleason/LogbookKonni_pi.git  DONE  /leamas. [PR](https://github.com/rgleason/LogbookKonni_pi/pull/40) Merged
https://github.com/rgleason/FindIt_pi.git  DONE /leamas [PR](https://github.com/rgleason/FindIt_pi/pull/5) Merged
https://github.com/nohal/vdr_pi.git       DONE
https://github.com/RooieDirk/NmeaConverter_pi.git  DONE 

=== Navigation
https://github.com/nohal/gecomapi_pi.git  DONE
https://github.com/rgleason/celestial_navigation_pi.git  PR merged  UPDATED rk
https://github.com/rgleason/route_pi.git  DONE /leamas [PR](https://github.com/rgleason/route_pi/pull/2) Merged
https://github.com/Rasbats/DR_pi.git    DONE
https://github.com/Rasbats/otcurrent_pi.git   DONE

=== Safety
https://github.com/jongough/ocpn_draw_pi.git   DONE
https://github.com/rgleason/watchdog_pi  DONE? RICK: can you confirm? Will check.
https://github.com/Rasbats/sar_pi.git DONE

=== Sailing
https://github.com/rgleason/tactics_pi.git
https://github.com/rgleason/plots_pi.git  DONE /leamas [PR](https://github.com/rgleason/plots_pi/pull/5) Merged
https://github.com/rgleason/polar_pi.git   DONE  /leamas [PR](https://github.com/rgleason/polar_pi/pull/6) Merged
https://github.com/jongough/windvane_pi.git  DONE

=== Weather
https://github.com/rgleason/weatherfax_pi.git
https://github.com/nohal/iacfleet_pi.git   DONE
https://github.com/rgleason/climatology_pi.git  DONE /leamas [PR](https://github.com/rgleason/climatology_pi/pull/20) Merged
https://github.com/rgleason/weather_routing_pi.git DONE /leamas [PR](https://github.com/rgleason/weather_routing_pi/pull/80) Merged

=== Utility
https://github.com/rgleason/statusbar_pi.git  DONE /leamas [PR](https://github.com/rgleason/statusbar_pi/pull/7) Merged
https://github.com/rasbats/calculator_pi.git   DONE
https://github.com/nohal/launcher_pi.git           DONE
https://github.com/nohal/ocpndebugger_pi.git  DONE
https://github.com/rgleason/pypilot_pi.git DONE. [PR](https://github.com/rgleason/pypilot_pi/pull/16) Merged
https://github.com/Rasbats/shipdriver_pi.git   DONE
https://github.com/TwoCanPlugIn/TwoCanPlugIn   DONE
https://github.com/LennartG-Sve/GPS-Odometer_pi.git  DONE

BETA
https://github.com/TwoCanPlugIn/EngineDashboard.git DONE
https://github.com/TwoCanPlugIn/RacingPlugin.git  DONE. See #15
https://github.com/RooieDirk/Deviation_pi.git  DONE
https://github.com/rgleason/Autopilot-Plugin.git  DONE. [PR](https://github.com/rgleason/Autopilot-Plugin/pull/2) Merged
https://github.com/douwefokkema/AutoTrackRaymarine_pi.git  DONE
https://github.com/rgleason/autopilot_route_pi.git  DONE /leamas [PR](https://github.com/rgleason/autopilot_route_pi/pull/3) Merged
https://github.com/rgleason/admiralty_tide_tables_pi.git  DONE  /leamas [PR](https://github.com/rgleason/admiralty_tide_tables_pi/pull/2) Merged
https://github.com/Rasbats/TideFinder_pi.git   DONE
https://github.com/Rasbats/survey_pi.git  DONE
https://github.com/Rasbats/otidalroute_pi.git  DONE
https://github.com/Rasbats/SailawayNMEA_pi.git  DONE
https://github.com/Rasbats/UKTides_pi.git          DONE
https://github.com/Rasbats/otidalplan_pi.git   DONE
https://github.com/Rasbats/EarthExplorer_pi.git  DONE

**Comment by leamas** [comment]
hm... status:
   - Some of Dave's plugin could IMHO be left out. They simply are not used enough to be available in the Plugin Manager. Marked WONTFIX
   - One or two of Mike's plugins, no big deal.
   - Around 20 of Rick's plugins. 
   

Conclusion: @rgleason  needs a hand or two. No problem, but first: Rick: Please update list above so all can see what's happening to avoid collisions.

EDIT: As far as I can see, watchdog looks fine and could be marked DONE.

**Comment by rgleason** [comment]
Cool, we can edit another person's comments?  That makes a good tool!

I've made some marks above, pretty obviously I am slower than you guys, but I think I've got the hang of it.
RE: bdbcat's   NVcharts  are they still working and available?  I thought I saw a CF request a little while ago.
Also regarding the others, Fagowi  charts are no longer available, but I think we should be fixing the others if there is any chance they'll be used, just to keep all the plugins in the same format.  Then we can remove the plugins from the wiki entirely. That would make me very happy.

**Comment by leamas** [comment]
@rgleason: Which is the next plugin you intend to work with? Please mark it "UNDER WAY - rick" or so above. 

EDIT: OK, I read your "will do" as UNDER WAY, and updated it. More in #8

**Comment by Rasbats** [comment]
@rgleason : Rick, stay safe. The path for Henri looks "interesting".

**Comment by rgleason** [comment]
Thanks.

The models are all confused by this hurricane. The landfall eye went west yesterday and then last night the models started showing the location going east again. Now it is modeled to go over Point Judith, the fishing town at the end of RI's favorite 19 mile stretch of stellar beach. If it does indeed landfall there, we get more rain, lower wind speeds and wind going offshore (from the north), so hopefully the surge won't be as much. 

Hurricane Bob, 30 years ago,  landed at Marion, Ma.  We still had 2 half hulls in Watch Hill Harbor and a half dozen sunk Watch Hill -15's and Nell weathered that one ok on her 300 lb mooring with lots of scope totally stripped including the boom.   After helping my mother batten down, we slept on the boat until 2 pm when were all evacuated, and then left for Boston.

PS: Good news we've been downgraded to "Tropical Storm Warning" !   It's going over Point Judith I guess.  We are on the kinder half of the hurricane.

11:09 am  Big winds and huge deluge of continuous rain. Hope the sump pump keeps working in the basement.
11:35 am  Power keeps flickering.  Westerly shoreline power is being shut down by the Police.
3:47 pm We passed through the eye, the backside has moved east, so we are out of it now. No damage here, going to Westerly this pm.

**Comment by leamas** [comment]
We are basically done here besides weatherfax_pi and  tactics_pi.  @rgleason : Are you working on these?

**Comment by leamas** [comment]
I have added tactics and weatherfax as well. This mean that we are done for now. However, here is a huge task to get the changes in our forks upstreamed.  I plan to look into this, but we might as well wait for a while to let the dust settle first.

**Comment by rgleason** [comment]
Alec  Thank you for the link fixes and site.yml improvements to many PI.  I think I have merged the majority of them.
I will use the site.yml changes as and example to improve celestial_navigation_pi manual next.

I have not had time to get into tactics, dashboard_tactics or weatherfax, but I think you did some fixes on these too.

**Comment by leamas** [comment]
All of your repos besides celestial runs cleanly with no link errors from  the forks I did my PRs from. I have also cleaned up the structure, all in the same way. You'll notice.

My hands are now full, I'm in the process of transferring the repos where you have accepted my PR  to you. This is, that the overall plugins manual is built from your repos  instead of my (our) forks at opencpn-manuals.

**Comment by leamas** [comment]
@rgleason : The most pressing issue now is a large number of link errors in celestial. Are you looking into those?

**Comment by leamas** [comment]
We have basically moved beyond this issue. Closing
