### ISSUE TITLE
Plugin manuals: Simplify paths and config

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#13]
As I see it, plugin manuals could be simplified and streamlined in two ways:

  - The directory level below _manual/_ for example _manual/oesenc_ does not really serve any purpose  and could be dropped.
  - By renaming the first and often only adoc file to index.adoc the need to define the start_page key in antora.yml can be dropped. It also streamlines plugin manuals, a good thing in its own.

I intend to do these simplifications in the plugins I work with unless there are arguments against.

**Comment by Rasbats** [comment]
No problem. But where the manual has several pages, like radar_pi there will be a lot of links to change.

**Comment by leamas** [comment]
Probably not, it's not that common that other pages refers to index, it's usually the other way around. The linkchecking will catch possible problems, which are solved wit h simple search/substiture.

**Comment by rgleason** [comment]
If this works, it would be a good thing.
Site.yml would then be
```
sources:
  -url: ../
   no start path needed if use index.adoc  rather than <plugin>.adoc
```

By the way weather_routing has several pages, the main one and two or three others.
Can't we still do it this way?

PS: Have been stripping the boat for Hurricane Henri which is headed to Groton, basically right where we are. Boat is being hauled 1st thing tomorrow. Luckily she's on the wait list for the yard.

**Comment by leamas** [comment]
Have you still not been able to get a working site.yml? If so, I can make a PR tomorrow.

**Comment by rgleason** [comment]
Have a working site.yml.   Have made changes to watchdog and pushed them
See  https://github.com/opencpn-manuals/plugins/issues/8#issuecomment-902372587

**Comment by leamas** [comment]
We have a workinng , accepted way to simplify paths. Many, perhaps most, plugins have already used it. No point having this issue open (please re-open if required)

**Comment by Rasbats** [comment]
>I intend to do these simplifications in the plugins I work with unless there are arguments against.

@leamas : Can you confirm the standards you have been working to:
1. Use index.adoc in the ROOT folder.
2. Drop the start-page key.
3. Simplify the folder structure.
4. If a plugin is still using a fork, make the PR. If/when accepted change sources.state to reflect where the plugin manual is now coming from. Working towards no opencpn-manuals forks?

Is there a reference plugin that you have completed that can be used as an example?

Intend tidying my stuff over the next few days. As you may have seen I am using the wiki as a scratch pad to save useful tips you have given.

**Comment by leamas** [comment]
>  Use index.adoc in the ROOT folder.

Yes

>  Drop the start-page key.

~No. This is possible, but I have been using the manuals/ prefix~
EDIT: yes.

>    Simplify the folder structure.

Yes, by dropping the directory below manuals. For example the _manual/polar_pi_ is gone, it's just  _manual_.

>  If a plugin is still using a fork, make the PR. If/when accepted change sources.state to reflect where the plugin manual is now coming from. Working towards no opencpn-manuals forks?

Yes, eventually there should be no opencpn-manuals forks.

> Is there a reference plugin tha

Any of Rick's which have accepted my PR, for example polar_pi

**Comment by leamas** [comment]
I'm closing this, we have basically advanced beyond it in #22 and #23
