### ISSUE TITLE
Unable to get local build to recognise changes

### ISSUE THREAD

**Issue by Rasbats** [opencpn-manuals/plugins#14]

**Comment by leamas** [comment]
Have you tried to   

    1. ./source-state.sh update
    2. ./source-state.sh save
    3. remove sources/xxxx ´, the plugin which fails to update
    4. ./source-state.sh restore
    
Please check that the commit save in sources.sh is the right one i. e., the same as the top commit in the plugin.

**Comment by Rasbats** [comment]
But there is no sources folder available.  Sources with .gitkeep stops it being used.

Tried renaming sources to sources.bak. restore then works but local build again does not work.

**Comment by leamas** [comment]
> But there is no sources folder available. Sources with .gitkeep stops it being used.

"Confused" could you expand a little?

**Comment by Rasbats** [comment]
Ok ... local build requires a sources folder with all the sources listed in it. (for me!)

To try and include those sources I had to "delete" sources folder and then build it again with restore. No .gitkeep then in sources.

**Comment by leamas** [comment]
"listed" in the sense that they are checked in in git? or?

**Comment by leamas** [comment]
You can re-create .gitkeep any time. It's an empty file, `touch sources/.gitkeep` in linux or Git Bash.

**Comment by Rasbats** [comment]
Yes ... they were checked in.

Just found:
Using your edit_url line allowed me to remove the link error. 

I am wondering if somewhere in the scripts we are not using antora --fetch which results in using something cached previously.

**Comment by Rasbats** [comment]
Off for a break.

**Comment by leamas** [comment]
Or, interesting, after removing the sources directory you can check it out again: `git checkout sources/.gitkeep`will restore the empty sources directory, unless you have checked in the removal of .gitkeep.

I'm off any time as well, waiting for GF/wife

**Comment by leamas** [comment]
bbl

**Comment by Rasbats** [comment]
I am still wondering about whether --fetch and (?) --stacktrace are needed to prevent the github cache being used.

I will revert the last two commits (for vfkaps) and take vfkaps out of the site.yml.

Enough for one day.

**Comment by leamas** [comment]
The antora cache has is not involved here. The only thing it sees are sources on the local file system, and to cache those would just be silly and it doesn't.

The thing is to revert to a clean state. Something like this

First, make sure there are no checked in git sources. First, clear tthe sources dir:  ` rm -rf sources/*`. Now, check with `git status` If it complains that anything is deleted like _Deleted: sources/foo_, then remove it from the index: `git rm -rf sources/foo`

Now everything in sources is removed from git. Next step is to re-create .gitkeep and check it in:

     $ touch sources/.gitkeep
     $ git add sources/.gitkeep
     $ git commit -am "Re-add sources/.gitkeep"

So, now it's clean. Verify like this:

    $ rm -rf sources   # Removes the whole thing from working area
    $ git checkout sources

There should now only be a .gitkeep file in the sources dir. If there is anything else: `git rm -r sources/foo`

You now have a clean sources directory, same as the builder. Populate it using `./source-state.sh restore` and all should be fine.

There is just one catch: I'm not completely sober when writing this....

**Comment by rgleason** [comment]
Leamas you make me chuckle.

**Comment by Rasbats** [comment]
@leamas : Cleaned up and working again.
