### ISSUE TITLE
painful merge ahead

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#16]
@rasbats: I don't think working in separate branches is viable in the long run. Eventually, the branches must be merged, it is probably already painful and even more so if we continue like this.

**Comment by Rasbats** [comment]
Agree. I am working in main. oplaydo can be deleted.

Now trying to fork my repos into opencpn-manuals, VFKaps is causing me issues. Hoping to follow your lead with the forks you have made.

Also unable to sort out the list of plugins in master-plugins:
```
AIS / Radar

    AISradar Display # managed plugin

    Radar Display # managed plugin === Charts

    oeSENC managed plugin

```

**Comment by leamas** [comment]
My strategy for forking:

- Fork the original repo, not a fork
- If applicable, copy contents from your fork where the manual is.

**Comment by leamas** [comment]
OTOH, since we are both working in main this is not an issue as I thought. Closing
