### ISSUE TITLE
top-level junk? Various sources* files around.

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#18]
Wa have files like ordered.sources.state, source-sparse*, source.sparse.beta* etc in top-level directory. All of these seems to be created by Mike.

Same applies to dokuwiki plugins.txt in the main directory.

@Rasbats :  could you look into this, either removing these files or add  a short comment about what it is doing?

**Comment by Rasbats** [comment]
@leamas : I will remove these files.

**Comment by Rasbats** [comment]
> I will remove these files.

Done.

**Comment by leamas** [comment]
Thanks!
