### ISSUE TITLE
VDR_pi - fork from the wrong source

### ISSUE THREAD

**Issue by Rasbats** [opencpn-manuals/plugins#19]
When starting work on the VDR manual the repo used was a fork from @nohal.

Rick is now managing this repo, a fork of @sethdart work.

My mistake ... I forked the @nohal version into opencpn-manuals and made changes. 

Intention is to rename the fork in opencpn-manuals, then fork the VDR plugin from @rgleason, update and make the PR to Rick.

When this is accepted the forks in opencpn-manuals will be deleted and site.yml and sources.state updated.

**Comment by rgleason** [comment]
OK thanks

**Comment by leamas** [comment]
@rasbats: You actually don't need to rename it, you can just fiddle with different remotes and branches within the same repo.

**Comment by Rasbats** [comment]
Fixed.
