### ISSUE TITLE
Windvane misssing site.yml causing failure to build  

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#20]
Not able to check links.
Have made a PR to Jon.

**Comment by leamas** [comment]
If the assumption is that a site.yml s required in a plugin like windvane for the overall build to work, this assumption is wrong. The site .yml is only used when making a local build in the plugin. 

Which means that this issue probably should be closed

**Comment by rgleason** [comment]
But Alec, missing site.yml in Windvane is causing the  [Link-Checker] to fail!!!!

https://github.com/opencpn-manuals/plugins/issues/8#issuecomment-907898746

https://github.com/opencpn-manuals/plugins/issues/8#issuecomment-907864475

An idea so that Link-checkker can still run
https://github.com/opencpn-manuals/plugins/issues/8#issuecomment-907900292

Not closing, I cant run a Link Check without a fail due to Windvane error

**Comment by leamas** [comment]
Definitely not.  The linkchecker has nothing to do with the site.yml in any plugin

**Comment by rgleason** [comment]
Well look at the error report that I linked to.

**Comment by leamas** [comment]
> Well look at the error report that I linked to.

> > error: playbook file not found at /home/runner/work/plugins/plugins/site.yml

That error says that the overall site.yml is missing, it's obviously not related to any plugin.  This is (was) https://github.com/opencpn-manuals/main/issues/15 which is fixed, and builds are running fine.

**Comment by rgleason** [comment]
Thanks Alec
