### ISSUE TITLE
Using standard/simplified config

### ISSUE THREAD

**Issue by Rasbats** [opencpn-manuals/plugins#22]
Perhaps a checklist is needed for the plugins to show which are completed to the standard configuration:
1. Updated where @Rasbats can see that the plugin uses the standard)
2. PR for dev may already have been done. Awaits update for sources.state?

 === AIS/adar
https://github.com/opencpn-radar-pi/radar_pi.git DONE - PR needed for dev.
https://github.com/nohal/aisradar_pi.git
https://github.com/rgleason/rtlsdr_pi.git DONE
=== Charts
https://github.com/bdbcat/nvc_pi.git WONTFIX?
https://github.com/bdbcat/s63_pi.git
https://github.com/bdbcat/bsb4_pi.git WONTFIX?
https://github.com/bdbcat/oeSENC_pi.git  -See Roberto email 
https://github.com/bdbcat/oeSENC_pi.git  - added, See Roberto email
Future 0-chart - See Roberto email 
https://github.com/bdbcat/ofc_pi.git WONTFIX?
https://github.com/Rasbats/photolayer_pi.git DONE
https://github.com/Rasbats/vfkaps_pi.git DONE
https://github.com/rgleason/rotationctrl_pi.git DONE - [PR pending](https://github.com/rgleason/rotationctrl_pi/pull/2)
https://github.com/rgleason/chartscale_pi.git DONE
https://github.com/nohal/objsearch_pi.git
https://github.com/rgleason/projections_pi.git DONE

=== Logs
https://github.com/rgleason/dashboard_tactics_pi.git
https://github.com/rgleason/LogbookKonni_pi.git  DONE - [PR pending](https://github.com/rgleason/LogbookKonni_pi/pull/40)
https://github.com/rgleason/FindIt_pi.git DONE - [PR pending](https://github.com/rgleason/FindIt_pi/pull/5)
https://github.com/nohal/vdr_pi.git DONE
https://github.com/RooieDirk/NmeaConverter_pi.git DONE - PR needed for dev repo

=== Navigation
https://github.com/nohal/gecomapi_pi.git DONE - needs adding to plugins and PR to dev.
https://github.com/rgleason/celestial_navigation_pi.git DONE
https://github.com/rgleason/route_pi.git DONE
https://github.com/Rasbats/DR_pi.git DONE
https://github.com/Rasbats/otcurrent_pi.git DONE

=== Safety
https://github.com/jongough/ocpn_draw_pi.git DONE - [PR pending](https://github.com/jongough/ocpn_draw_pi/pull/479)
https://github.com/rgleason/watchdog_pi 
https://github.com/Rasbats/sar_pi.git DONE

=== Sailing
https://github.com/rgleason/tactics_pi.git  DONE - [PR pending](https://github.com/jongough/ocpn_draw_pi/pull/479)
https://github.com/rgleason/plots_pi.git DONE - [PR pending](https://github.com/rgleason/plots_pi/pull/5)
https://github.com/rgleason/polar_pi.git DONE
https://github.com/jongough/windvane_pi.git 

=== Weather
https://github.com/rgleason/weatherfax_pi.git DONE
https://github.com/nohal/iacfleet_pi.git DONE
https://github.com/rgleason/climatology_pi.git DONE
https://github.com/rgleason/weather_routing_pi.git  DONE

=== Utility
https://github.com/rgleason/statusbar_pi.git DONE - [PR pending](https://github.com/rgleason/statusbar_pi/pull/7)
https://github.com/rasbats/calculator_pi.git  DONE
https://github.com/nohal/launcher_pi.git DONE - PR needed for dev.
https://github.com/nohal/ocpndebugger_pi.git DONE - PR needed for dev.
https://github.com/rgleason/pypilot_pi.git DONE
https://github.com/Rasbats/shipdriver_pi.git DONE
https://github.com/TwoCanPlugIn/TwoCanPlugIn DONE - PR needed for dev.
https://github.com/LennartG-Sve/GPS-Odometer_pi.git DONE - PR needed for dev.

BETA
https://github.com/TwoCanPlugIn/EngineDashboard.git DONE - awaiting PR so edit points to dev repo
https://github.com/TwoCanPlugIn/RacingPlugin.git DONE - awaiting PR so edit points to dev repo
https://github.com/RooieDirk/Deviation_pi.git DONE - awaiting PR so edit points to dev repo
https://github.com/rgleason/Autopilot-Plugin.git DONE
https://github.com/douwefokkema/AutoTrackRaymarine_pi.git DONE - not yet using devs repo for edit - PR?
https://github.com/rgleason/autopilot_route_pi.git DONE
https://github.com/rgleason/admiralty_tide_tables_pi.git DONE
https://github.com/Rasbats/TideFinder_pi.git DONE
https://github.com/Rasbats/survey_pi.git DONE
https://github.com/Rasbats/otidalroute_pi.git DONE
https://github.com/Rasbats/SailawayNMEA_pi.git DONE
https://github.com/Rasbats/UKTides_pi.git DONE
https://github.com/Rasbats/otidalplan_pi.git DONE
https://github.com/Rasbats/EarthExplorer_pi.git DONE

**Comment by leamas** [comment]
hm... seems like all plugins now either are updated or have a pending PR. Time to close this, leaving open stuff in   #23?

**Comment by Rasbats** [comment]
>Time to close this, leaving open stuff in #23?

Agree. Closing.
