### ISSUE TITLE
Updates of Manuals - rgleason

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#25]
Watchdog -done, but refining
Weather_routing -done, but refining
Celestial_Navigation -done
Weatherfax
Climatology - done
Polar -done
Plots -done
Statusbar - Done
Dashboard_tactics.
AisRadar - Done pavel needs to accept pr
Squiddio -Done mauro needs to accept pr
Tactics
Vdr -done
Find-it -done
Logbook -done
Rotationctrl -done
Projections-done
Rtlsdr - done
Pypilot -done
Chartscale -done
Nmeaconverter

https://github.com/opencpn-manuals/plugins/issues/8

**Comment by leamas** [comment]
As things are now  aisradar is owned by Pavel, changes goes through a PR against https://github.com/nohal/aisradar_pi. He has been extremely responsive to PRs.

**Comment by Rasbats** [comment]
Before I saw the @rgleason fork of sQuiddio I added it to the manual as a module. Rick ... you could use this as a starting point. Please remove my module in master-plugins when you are ready.

**Comment by rgleason** [comment]
Thats fine about aisradar. It is not pavel though it is verazano. Furthermore I have been updating testplugin fe and recently updated it with svg icon improvements and pushed to verazzo. So it is confusing. Pavel has not always accepted my pr but I dont care I push to verrazano. I intend to review the documentation anyway.

**Comment by rgleason** [comment]
At rasbats, re squiddio. Push to mauro or me your choice. I update squiddio with TP frontend and push to mauro. He has not done deployment, I have.  I intend to review squiddio manual.

**Comment by leamas** [comment]
The general rule should always be to push to the "real" upstream as long as it is not dead. This applies here, and we should use Mauro's repo.  But it's not only about where to push,it's also about pointing out the correct repo in site.yml.

I'll file a new bug, this is not only about sQuiddio.

**Comment by rgleason** [comment]
Fixed squiddio headings and pushed to mauro..

**Comment by rgleason** [comment]
Standard/Simplified manual config  (fix)
These need to be fixed.
aisradar - done  pushed to nohal and verazano
chartscale
watchdog

also windvane -  done pushed to jongough

**Comment by rgleason** [comment]
aisradar, chartscale, windvane  formatting, index.adoc, site.yml and directories fixed, added .gitignore   for doc too..
Have watchdog left to do.

**Comment by Rasbats** [comment]
@rgleason : watchdog_pi: Updated sources.state and site.yml for your latest commit. Needed to edit plugins.adoc and nav-plugins.adoc to use index.adoc iso watchdog.adoc.

**Comment by rgleason** [comment]
Thanks very much. There may be others too. How do we find those?

**Comment by Rasbats** [comment]
You have a clone of opencpn-manuals/plugins. There are four files to look at.

1. Does sources.state point to the latest managed repo?
2. Does site.yml have the correct edit_url for that repo?
3. Check nav-plugins.adoc. For instance watchdog_pi had an entry `** xref:watchdog::watchdog.adoc[Watchdog]`. Edited to read:
`** xref:watchdog::index.adoc[Watchdog]`
4. Check plugins.adoc to see if a similar edit is needed.

WRT 3 & 4 With a cursory check I don't see any problems with your repos. It is probably 1 & 2 that need an edit. Then push to main with [full-linkcheck] and `git push -f origin main:build`

**Comment by leamas** [comment]
> `git push origin main:build`


i. e., `git push -f origin main:build`

**Comment by Rasbats** [comment]
@rgleason : Started to look at your commits in sources.state. 
Some of the linkcheck problems may stem from old commits.
e.g. sources.state autopilot_route : commit `c6baf5995f3f41bf387536b8572ae1086ac0eee4`
Latest at [https://github.com/rgleason/autopilot_route_pi](https://github.com/rgleason/autopilot_route_pi) : ed3b8469ada185ffaa77cf9be790928b6376cdf6

If you are not working in the plugins repo do you want me to update your commits in sources.state and edit site.yml if needed?

**Comment by rgleason** [comment]
Yes please. 

I have now finished editing plugins in my repos.
I have gotten on my direct local clone of opencpn-manuals/plugins  and done 
git pull origin main   - so it should be current shouldn't it?

In looking through sources.state and site.yml  I realize that four pages of weather_routing_pi not be included in the linkcheck. Those are

..weather_routing_pi\manual\modules\ROOT\pages\configuration_defaults.adoc
..weather_routing_pi\manual\modules\ROOT\pages\help_information.adoc
..weather_routing_pi\manual\modules\ROOT\pages\irma_examples.adoc
..weather_routing_pi\manual\modules\ROOT\pages\polar_file_conversion.adoc

Should they be added to the site.yml?

Regarding the files nav-plugins.adoc and  plugins.adoc ,  where do I find those?
 They do not seem to be available in my local opencpn-manuals/plugin which is current.

Also I notice that the plugins are largely under  "sources" and for most of the pi there is a "manual" directory.
Is it possible or adviseable to edit those or not?
I suppose if those are edited the source files then become old and diverged, so it is best not to edit those.

**Comment by Rasbats** [comment]
@rgleason : plots_pi latest commit now in sources.state.
>Regarding the files nav-plugins.adoc and plugins.adoc , where do I find those?

C:\Projects\opencpn-manuals\plugins\manual\master-plugins\modules\ROOT\pages
C:\Projects\opencpn-manuals\plugins\manual\master-plugins\modules\ROOT\partials

>Should they be added to the site.yml?

No!

>Is it possible or adviseable to edit those or not?

No, These manual lines should all be correct except for ais_radar_display. PR pending for Pavel.

**Comment by Rasbats** [comment]
@rgleason : sources.state updated for latest commit for FindIt_pi.

**Comment by leamas** [comment]
@rasbats @rgleason 

As I see it, this is a mess which doesn't work. To be frank, the core problem here is that Rick isn't up to speed with git enough to handle the somewhat complex central parts of opencpn-manuals/plugins.  Until Rick has worked more with git and got some more skills on this, perhaps we could work like this (?):

  - Rick updates and pushes his plugins, exactly as other plugin maintainers do with their plugins.
  - Mike handles all changes of the central opencpn-manuals/plugins.
  - Part of Mike's job is to now and then run `./source-state.sh update` which picks up all changes pushed to plugin repos.
  - I try to keep my hands off, and don't change anything unless having talked to Mike about it.

This means that everything works without Rick having to meddle with the messy parts. In a longer perspective, we should see that Rick can handle also changes to opencpn-plugins, though.

Thoughts?

**Comment by Rasbats** [comment]
The only repos causing a **local build** problem are Deviation, ais_radar_display and objsearch. Github pages compiles everything without complaining.
Deviation awaits a PR being accepted.
aisradar also has a PR pending.
objsearch needs updating for the standard config. I will make this PR to Pavel from my own fork.

>perhaps we could work like this (?):

Fine at this end.
@rgleason : You have a PR for weather_routing. Suggest running an empty [full-linkcheck] to show any remaining link errors. When time here allows you may find some more PR coming your way.

**Comment by rgleason** [comment]
I know how git works and have learned and am learning about opencpn-manuals/plugins operation. I will review those changes mike and perhaps make them manually. I think the link to plugin installation needs to be changed in my other plugins if the current one does not work.

**Comment by rgleason** [comment]
Btw I fixed the problems that I could, findit and others in my scope

**Comment by rgleason** [comment]
I will continue to learn, despite your request.

**Comment by leamas** [comment]
@rgleason 

> I will continue to learn, despite your request.

Of course, don't get me wrong. I just propose how to work while you are dong this.. Is it OK as proposed? For now?

**Comment by leamas** [comment]
> I know how git works 

Those are big words...  git is an extremely complex and also flexible SCM tool. Personally, I would not say that I _know how git works_...

**Comment by rgleason** [comment]
NoOn Sep 11, 2021 3:33 PM, leamas ***@***.***> wrote:
@rgleason

I will continue to learn, despite your request.

Of course, don't get me wrong. I just propose how to work while you are dong this.. Is it OK as proposed? For now?

**Comment by leamas** [comment]
@rgleason  :  ?

**Comment by rgleason** [comment]
I know what I am doing.

**Comment by leamas** [comment]
Of course,  I don't think anyone is questioning that. At least not me, for sure.

My question mark was just about  https://github.com/opencpn-manuals/plugins/issues/25#issuecomment-917477212 which I just not understand.

This aside, I read your remarks as if you don't agree with the roles and workflow proposed [above](https://github.com/opencpn-manuals/plugins/issues/25#issuecomment-917358594). If so, have you another proposal how we should organize this?

In any case, we should avoid personal attacks. If this is what  you perceive that I'm doing I apologize, that was not my intention.  English is certainly not my native language and nuances are sometimes not what they should be.

**Comment by rgleason** [comment]
Alec I accept your apology. I have an alergic reaction sometimes in this environment and it may become too toxic for me to continue to work.

**Comment by leamas** [comment]
Right. As I understand it, the problematic environment is git rather than asciidoc/antora. 

The way to avoid this reaction might be as I proposed: that you from the beginning starts with maintaining your plugins. This is just the ordinary edit-commit-push, and by doing this you can focus on the contents. 

Working with the developer manual is the same, besides that the risk is higher that others are working concurrently and the related need to occasionally rebase.  This is a little more complex than the plugin manuals, but not that much.

But let's face it: the overall plugins manual is a complicated mess. Since Mike handles it now, why not wait with handling this for the very moment?  OK?

**Comment by rgleason** [comment]
You can understand then why I say this environment appears to be more fragile than dokuwiki, yet you yourself have said that git history is never lost.  

I find I can work with both asciidoc/antora and git,  I've been using git almost 7 years now, and I've fiqured out how to get out of some pretty difficult siruations, antora/asciidoc is newer, so I find some of your "rational" kind of backwards.

As I said earlier, I have allergies to exactly what you did. If you want my help, the environment will have to be free of those toxins.

End of discussion

**Comment by leamas** [comment]
> End of discussion

We have one loose end, at least:  Is ok to work as I propose for now, to get around the sharp corners?

**Comment by rgleason** [comment]
That's fine. This has gotten to be too toxic, and I have plenty of other things to do. Bye.

**Comment by Rasbats** [comment]
@rgleason : Rick ...
You are not the only one thinking "Is this worth it". I went through that wall a few days back. Some perspective might be needed.
A lot of ground has been travelled since starting this investigation of asciidoc/antora. It started with the direct use of the manual from the latest commit of the dev repo. Perhaps a better initial spec for the configuration would have helped avoid a lot of the later edits and PR but that is how software projects often progress. I had to learn "on the job". A lot of the extra work is due to my lack of  knowledge.

In order to provide an audit trail Alec came up with the use of the sources.state file. I did not see how a URL could be made into a source module for the plugins manual but the build-and-deploy script does this. The sources.state file acts as a log of changes to the plugin repos.  We can look back at edits to the dev repo manuals in the same way that we can look back at previous edits in Dokuwiki. 

Because of the flexibility of asciidoc/antora Github has embraced this markup language. You can use asciidoc for the READ.ME file if you start a new repo. More tools to work with asciidoc will follow.

The ability to quickly make an HTML file for a plugin means that the plugin developer can create a help file they can incorporate in their work, with a "Help" button or menu option. A further development could be direct access for help for an individual plugin from OpenCPN. This is what a lot of programs already offer. 

Imperfect in places but we now have a plugins manual that shows the information the user might need:
[https://opencpn-manuals.github.io/plugins](https://opencpn-manuals.github.io/plugins)

I think the product justifies the many hours spent with this project.
