### ISSUE TITLE
Most plugins: Wrong initial heading level ==

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#26]
For some reason most plugins have their first heading with a == level.  For example, the Sar plugin has

    == SAR (Search and Rescue)

This confuses antora, which expects the first heading to be just '='. One consequence of this is that the HTML page title is undefined, and that the browser thus presents the page as something like _Untitled :: OpenCPN_.

Although it 's probably possible to mess around in the ui bundle to cope with this it would be a band aid. The proper fix is a new round of PR to all plugins.  OTOH, this is not that  urgent, and we could wait to see if there are other things which need to go to such PRs

**Comment by leamas** [comment]
I have updated the PRs in #23 which are still open and I have write access to. That should fix  about 16 plugins...

**Comment by Rasbats** [comment]
14 of mine can be corrected pretty quickly. I will also take the 4 that are in "Included Plugins".

**Comment by leamas** [comment]
Thanks! I have already fixed the included omes.

**Comment by Rasbats** [comment]
Just about to say that someone had been there! Thanks.

**Comment by rgleason** [comment]
I am not where I can do this riht now. Using cell phone, long drive.

**Comment by rgleason** [comment]
Have updated "==" headings to 
squiddio
statusbar
weatherfax
rtlsdr
tactics
vdr
autopilot_route
polar
autopilot_plugin
pypilot
admiralty_tide
projections
climatology
chartscale
aisradar

There are a few of these plugins to reconfig with index.adoc and the standard site.xml etc.

**Comment by rgleason** [comment]
Have made PRs to vdr  seth dart (not accepting from Pavel or me)  and aisradar to verazano

**Comment by leamas** [comment]
I need to file PRs for pavel's plugins before  we can close this.

@Rasbats : Are you done here?

**Comment by Rasbats** [comment]
Yes.

**Comment by leamas** [comment]
OK, it's up to me then. Back later

**Comment by leamas** [comment]
> ave made PRs to vdr seth dart 

Indeed: https://github.com/SethDart/vdr_pi/pull/11

This is a PR where you ask him to merge 229 commits (!) with the single description "Update".  No sane person would give such a PR a review, it's just to throw away without even a look. 

That said, the last commit on this repo was 2015, and the last reply form the maintainer was 2016. He should IMHO at least reject your PR, perhaps without comments. But still.

Taken together  this indicates that this upstream is dead.

**Comment by Rasbats** [comment]
@leamas : 
Looking at the list of plugins needing finishing again I will get sQuiddio sorted when Mauro has accepted the PR fom Rick.

**Comment by rgleason** [comment]
Neither seth dart or pavel have accepted my pr s for vdr. I will cancel both now and advise that both of you wotked on rgleason/vdr as well as me. And the rgleason/vdr is what is deployed. Niether seth dart or pavel do that.
Therefore rgleason/vdr should be the repos used lmho

**Comment by rgleason** [comment]
I have closed those PR. There were no conflicts.

**Comment by rgleason** [comment]
Also with regard to aisradar. Niether verazano or nohal are deploying. The deploy is from rgleason.

**Comment by leamas** [comment]
When it comes to vdr I agree that the upstream is dead, and that we should use your fork there. This is also how site.yml is configured now, it points to your fork.

**Comment by leamas** [comment]
As for aisradar the current setup in site.yml uses nohal's repo. He has accepted my PRs pronto, so it might make sense to keep this setup (?)  I cannot see any PR from you at his repo.

Now, nohal is certainly not the original upstream. But if we can involve other devs in the maintenance this is a huge advantage. The real  problem here is not the initial manual, it's the maintenance.

**Comment by rgleason** [comment]
I agree completely Alec.  
It would be wonderful if Pavel could find some time to actually set up the build and deploy part.
I had hoped that Sean would pick that up too, and I tried to guide him, but he shows little interest in that part.
So lets keep aisradar with Nohal, I will PR to both him and Verazano who built the plugin and does accept PR's but does not build and deploy either.

**Comment by rgleason** [comment]
Can this be closed now?

**Comment by leamas** [comment]
No, I have some homework to do. I'll take of it when done

**Comment by leamas** [comment]
When you make yout PR, make sure they only update the manual directory and are sane in an overall sense (just a few commits).

**Comment by rgleason** [comment]
@ leamas and @rasbats

` I will get sQuiddio sorted when Mauro has accepted the PR fom Rick.`

I have prepared more changes to finish the squiddio manual and will push those to him

**Comment by rgleason** [comment]
He just wrote me. I have to write back to show him where the pr is.
