### ISSUE TITLE
Use correct plugin upstreams.

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#27]
We should have a general rule to use the original repository for  the manual as long as this is not dead. Seemingly, this have failed in at least two cases (list might need to be edited)

  - squiddio is not even included in site.yml as of now. Here we should use Mauro's repo at https://github.com/mauroc/squiddio_pi.
  - For aisradar_pi site.yml points to Pavel's fork at https://github.com/nohal/aisradar_pi/. Here we should the  active upstream at https://github.com/Verezano/AISradar_pi.

See also #25

**Comment by Rasbats** [comment]
Until now squiddio has been a module in master-plugins. 
@rgleason now has a PR for the manual. He has work that needs pushing to [https://github.com/mauroc/squiddio_pi](https://github.com/mauroc/squiddio_pi). The manual should be passed across at the same time.

**Comment by Rasbats** [comment]
As noted elsewhere Sat2Chart (ge2kap plugin incorporated) does not have a repo. It will need to stay as a module in master-plugins.

**Comment by Rasbats** [comment]
Alec ... can you see a fix for this certificate problem?

https://squidd.io/	
Line: 852
Code: 500 Can't connect to squidd.io:443 (certificate verify failed)
To do: This is a server side problem. Check the URI.

**Comment by leamas** [comment]
Hm... I recognize this, been there. 

I think this is a problem in linkcheck, how it initiates the connection. Since the site obviously works fine from  browser, the real usecase, I suggest that you add squidd.io to the list of excluded domains in ci/w3c-linkcheck.sh 

PS:  #28 DS

**Comment by leamas** [comment]
@rgleason wrote https://github.com/opencpn-manuals/plugins/issues/28#issuecomment-910166501

I certainly understand. The first sentence in this issue's first comment is 

> We should have a general rule to use the original repository for the manual as long as this is not dead. 

The situations you describe are those defining a dead upstream

**Comment by rgleason** [comment]
What is "dead"?

**Comment by leamas** [comment]
Well, you have described it quite well. A dead upstream is a repo/community which no longer is active, doesn't  evolve, does not accept PRs without reasons, does not reply when approached, etc.
