### ISSUE TITLE
Authoring update

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#28]
@rasbats: I have made a major rewrite some of  the authoring stuff. I have made a build (under way as I write this), but not pushed it to main.

Could you make a quick review, and possibly stop me before I merge into main?

**Comment by rgleason** [comment]
Thers are some distinctions which need to be recognized that Alec does not understand.

1. Oeiginal pi authors disappeae .
2. Original pi authors may not accept pr.
3. Original pi authors may not be the ones maintaining and deploying.
4. PI maintenance changes hands and it handled in various ways.
5. pi authors loose interest.
That is the reality.

**Comment by Rasbats** [comment]
FAQ.adoc needs an edit for help file HTML. Still looking.

**Comment by leamas** [comment]
> Thers are some distinctions which need to be recognized that Alec does not understand.

I certainly do. However, this discussion belongs to #27.

**Comment by leamas** [comment]
>Still looking.

No hurry, unless you push to build and overwrite the  stuff.

**Comment by Rasbats** [comment]
@leamas : Probably better if you could merge to main. I need to do a lot of edits myself as well as looking at your stuff.

**Comment by leamas** [comment]
Fine with me. I just wanted to check that you don't mind removing the old stuff.

> probably better if you could merge to main

done

**Comment by Rasbats** [comment]
>How could images be displayed in Firefox using the asciidoc plugin?
    At the top of the document (.adoc) add the attribute ``:imagesdir: ../images/'' This will not appear in the page but controls the location of the images.

This is not needed on Windows when using the Firefox extension if you set the custom attribute in the extension to 
imagesdir=../images/. Shall I update for this? It would save devs from adding an unnecessary line. We want all the images to be in the images directory of the manual anyway.

**Comment by Rasbats** [comment]
Setting up Chrome and Firefox differ slightly. Intend adding a guide for this.

**Comment by leamas** [comment]
Great. I don't use these tools, so I have nothing to add here.

**Comment by leamas** [comment]
we have work to do, but things are merged so I close this one
