### ISSUE TITLE
rgleason/route_pi: Issues are not enabled

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#29]
Since we intend to use this repo as upstream (?), a situation where issues are not enabled becomes problematic

The need to enable issues applies to all upstream repos, should there be more in similar situation

As for  route_pi, it generates an antora error when building. It is fixed by following patch removing some dokuwiki junk which triggers the antora error.

```
From 88629c79b329d69326bf3d48c47734b3a23cbd13 Mon Sep 17 00:00:00 2001
From: Alec Leamas <leamas.alec@nowhere.nt>
Date: Wed, 1 Sep 2021 21:08:54 +0200
Subject: [PATCH] index.adoc: Remove dokuwiki cruft causing antora failure.

---
 manual/modules/ROOT/pages/index.adoc | 2 --
 1 file changed, 2 deletions(-)

diff --git a/manual/modules/ROOT/pages/index.adoc b/manual/modules/ROOT/pages/index.adoc
index 64b6b2a..1250ecd 100644
--- a/manual/modules/ROOT/pages/index.adoc
+++ b/manual/modules/ROOT/pages/index.adoc
@@ -1,5 +1,3 @@
-indexmenu_n_4
-
 = Great Circle Route
 
 == Links
-- 
2.31.1

```

EDIT: The PR at https://github.com/rgleason/route_pi/pull/3 obsoletes this patch.

**Comment by leamas** [comment]
@rgleason : ^

**Comment by leamas** [comment]
I was able to generate a [PR](https://github.com/rgleason/route_pi/pull/3) using the Edit This Page link. First time, works great!

**Comment by rgleason** [comment]
Great , sill enable issues

**Comment by leamas** [comment]
Yes. While on it, please check your other repos as well (I have not).

**Comment by leamas** [comment]
@rgleason:   can we close this?

**Comment by rgleason** [comment]
I've now gone through all of them and they have Issues now.
