### ISSUE TITLE
Install, enable and uninstall  for Plugin Installer (PI) and PI Manager (PIM)  

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#3]
Will there be a page for this?

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:install_and_enable

We also has a separate page for Linux Install of plugins

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:install_linux_plugins

**Comment by Rasbats** [comment]
This may be better in the user manual.

**Comment by rgleason** [comment]
Ok I think that will work.
