### ISSUE TITLE
Workflow explanation

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#30]
There are some aspects of this that are assumed which should be more explicit.
What is the situation here?
What repository should be used? 
https://github.com/opencpn-manuals/plugins/commit/f11e43150a0060c6c6611efb0e6dfd7f0dd79214

```
== Publish to Github Pages

Push the current branch to the branch _build_, something like

    $ git push -f origin HEAD:build

```

**Comment by leamas** [comment]
This is described in WORKFLOWS, the first heading which is about cloning. When working with plugins,
the repository is indeed git@github.com:opencpn-manuals/plugins.git as in the example.

Also see the first paragraph in INSTALL which refers to this.

**Comment by rgleason** [comment]
See  https://github.com/opencpn-manuals/plugins/issues/31#issuecomment-912927402
very good explanation by Alec.
