### ISSUE TITLE
How to get manual changes/updates in rgleason local/remote into opencpn-manuals/plugins

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#31]
Some changes in VDR for example.  Or squiddio?

Another perhaps different example is weather_routing 
https://opencpn-manuals.github.io/plugins/weather_routing/0.1/index.html
Which is not listed  here  https://github.com/opencpn-manuals/plugins/tree/main/manual/master-plugins/modules
however I believe the source repository being pointed to is  https://github.com/rgleason/weather_routing_pi/tree/master/manual  so the process used to update that is this?
https://github.com/opencpn-manuals/plugins/blob/main/WORKFLOWS.adoc#maintaining-dependencies-in-sources

[Complex changes on separate branch](https://github.com/opencpn-manuals/plugins/blob/main/WORKFLOWS.adoc#complex-changes-on-separate-branch)
Is this describing checking out a plugin from opencpn-manuals/plugins or something else?

```
When doing more complex changes using a separate branch makes things easier:

$ git checkout -b my-branch

```

[Maintaining dependencies in sources](https://github.com/opencpn-manuals/plugins/blob/main/WORKFLOWS.adoc#maintaining-dependencies-in-sources)
I realize that there are many ways to work, and it is difficult to fully describe these techniques, but what would the primary use example be for this process?   I think it is a way of initiating rebuild and update of the entire plugin manual and checking links with the use of [link check] etc...

**Comment by leamas** [comment]
This is about updating the sources.  First, make sure you have an updated main branch:

    $ git remote update origin
    $ git rebase origin/main

There might be conflicts. If so, avoid using "your" stuff when resolving. Then, update the sources:

    $ ./source-state.sh update
    $ antora site.yml

This gives an updated, local build. To push this and make a new build:

    $ git add sources.state
    $ git commit -m "Update sources to latest versions"
    $ git push -f  origin main:build

If everything looks sane, push also to main:

    $ git remote update origin
    $ git rebase origin/main
    $ git push origin main:main

EDIT: DON'T USE -f WHEN PUSHING TO MAIN!

**Comment by leamas** [comment]
In short:

  - Rebase your main branch in order to pick up changes in for example site.yml.
  - Use _./source-state restore_ to update your sources to match the main branch's after  a rebase.
  -  Use _./source_state.sh update_ to pick up changes you and others have pushed to plugins. 
  - After running  _./source_state.sh update_  , _sources.state_ is updated. You must commit and push these changes to keep the main branch sound.

**Comment by rgleason** [comment]
Thankyou.
Is there a script that has a list of the plugins being used for the manual for reference?

**Comment by leamas** [comment]
it's opencpn-manuals/plugins/site.yml

**Comment by rgleason** [comment]
Yes, and also sources.state  https://github.com/opencpn-manuals/plugins/blob/main/sources.state
which shows the repositories being used.

I assume this is automatically generated with the commit SHA?

**Comment by leamas** [comment]
For a given commit, sources.state is always the same. Which actually applies to all files included in the git repo.

**Comment by rgleason** [comment]
Thanks very much.

**Comment by rgleason** [comment]
Have gotten to
```
 $ ./source-state.sh update
 $ antora site.yml

```
```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ antora site.yml --stacktrace
Error: Local content source does not exist: C:\Users\Rick\documents\github\OM-plugins\sources\admiralty_tide_tables_pi (url: sources/admiralty_tide_tables_pi)
    at loadRepository (C:\Users\Rick\AppData\Roaming\npm\node_modules\@antora\site-generator-default\node_modules\@antora\content-aggregator\lib\aggregate-content.js:199:11)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async generateSite (C:\Users\Rick\AppData\Roaming\npm\node_modules\@antora\site-generator-default\lib\generate-site.js:18:39)
    at async run (C:\Users\Rick\AppData\Roaming\npm\node_modules\@antora\cli\lib\cli.js:17:21)
```

Perhaps this needs an update somewhere?   I have cloned it locally now and there was no difference.
As I understand it, this needs to be working locally first before I can push up to make a new build.

sources.state shows:

`./admiralty_tide_tables_pi https://github.com/rgleason/admiralty_tide_tables_pi.git edbca34e7c5f1a1b592756b2f3a3748bf4f7d5ad`

and  site.yml shows:
```
    - url: sources/admiralty_tide_tables_pi
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/rgleason/admiralty_tide_tables_pi/edit/master/{path}
```
Which look OK

LATER:
Ok because I did not have admirality_tides_pi  as a local repos when I first started, perhaps I have to repeat the beginning commands now that I have cloned.

LATER: 
Starting from the beginning didn't work.

LATER:
Tried removing my local  github/OM-plugins  and then cloned it again and followed the process until  "antora site.yml"
which resulted in the same error again.

**Comment by leamas** [comment]
When things goes bad: Reset the sources directory completely:

    $ rm -rf sources/*
    $ git checkout sources/.gitkeep
    $ ./source-state.sh restore

**Comment by rgleason** [comment]
OK
 rm -rf sources/*
git checkout sources/.gitkeep

```
Receiving objects: 100% (78/78), 2.79 MiB | 5.92 MiB/s, done.
Resolving deltas: 100% (6/6), done.
Updating files: 100% (87/87), done.
fatal: invalid refspec '972df1828c09a9166aba1258fdcbe02b65093ab3?'
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
Cloning into 'windvane_pi'...
remote: Enumerating objects: 80, done.
remote: Counting objects: 100% (80/80), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 80 (delta 0), reused 69 (delta 0), pack-reused 0 eceiving objects:  52% (42/80)
Receiving objects: 100% (80/80), 20.39 KiB | 2.27 MiB/s, done.
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 2 (delta 0), pack-reused 0
Receiving objects: 100% (5/5), 15.89 KiB | 5.30 MiB/s, done.
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
Receiving objects: 100% (28/28), 151.08 KiB | 2.40 MiB/s, done.eceiving objects: 100% (28/28)

Resolving deltas: 100% (6/6), done.
fatal: invalid refspec '963358ec9fc527be0c797c3b7f7f024c9fe8bfb4?'
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
```

**Comment by rgleason** [comment]
It appears that that fatal number is associated with sources.state      Windvane

./windvane_pi https://github.com/jongough/windvane_pi.git 963358ec9fc527be0c797c3b7f7f024c9fe8bfb4

What should I do, comment out windvane in the site.yml?

**Comment by rgleason** [comment]
BTW windvane needs updating for site.yml,  configuration and index.adoc
https://github.com/jongough/windvane_pi/tree/master/manual/windvane/modules/ROOT/pages

**Comment by Rasbats** [comment]
@rgleason : If you leave windvane as is I will take a look.

**Comment by rgleason** [comment]
Mike, I just finished fixing it. Will push to Jon.

**Comment by rgleason** [comment]
windvane manual changes pushed to jongough

**Comment by Rasbats** [comment]
@rgleason : I cancelled my PR for windvane! BTW you need a gitignore to stop the docs folder being included in the PR.
Edit: my fork of windvane is used in the plugins manual at the moment. When Jon has accepted your PR I will edit sources.state etc to point to his repo.

**Comment by rgleason** [comment]
The reason I started editing windvane was I got a failure as indicated[above](https://github.com/opencpn-manuals/plugins/issues/31#issuecomment-912999206)

Is there some way to fix this so that I can update weather_routing_pi and make sure that it is working right?
in the full manual?  

I will add a .gitignore  to jon next.

**Comment by Rasbats** [comment]
@rgleason : I had a successful build using my windvane repo. If you follow the sources-state.sh restore route again for a local build you should find things working (I hope).
Personally after making a commit with [full-linkcheck] in main I "git push origin main:build" and this results in a log of the build where errors can be tracked down. Haven't built locally for some time now.

**Comment by rgleason** [comment]
I haven't been able to build locally for some time now, there is always some problem, and I am unaware of another way.

How do you "using my windvane repo"??

So do you edit your local version of site.yml so windvane points to your version?

**Comment by rgleason** [comment]
Updated aisradar  (and pushed to verazano and nohal),  chartscale, and windvane (pushed to jongough)
for  .gitignore, removal of docs and removal of old manual/ais_radar_display directory

**Comment by rgleason** [comment]
Still have been unable to get my weather_routing_pi manual updated in the full manual because of these issues that I've been working on this afternoon.  Still have to fix the watchdog format etc...

**Comment by rgleason** [comment]
Have started this anew and now getting this error.

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ antora site.yml
error: the start path 'manual/chartscale' does not exist in C:\Users\Rick\documents\github\OM-plugins\sources\chartscale_pi (ref: HEAD <worktree>)
Add the --stacktrace option to see the cause.
```

**Comment by rgleason** [comment]
To fix the above problem I went into  site.yml and changed   chartscale start_path  to just "manual" not "manual/chartscale" and made a commit.

Then redid the whole command string again and ended with this error


```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ antora site.yml
asciidoctor: ERROR: index.adoc: line 7: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: index.adoc: line 33: level 0 sections can only be used when doctype is book
```

Quickly checked chartscale   index.adoc and I don't believe the error is there.  So where is it?

**Comment by leamas** [comment]
The error messages here are not easy to handle. See #33.

**Comment by leamas** [comment]
One overall problem here is that no-one has done a `./source-state.sh update; ./source-state.sh save`and committed the results.  I have done this now, and a lot of plugins are updated.

Without this step, changes in plugin repos are not reflected in sources.state.

To repeat: the steps to update opencpn-manuals/plugins after pushed changes in one or more plugins:

    $ ./source-state.sh update
    $ ./source-state.sh save
    $ git commit -am "sources: Update to latest versions"
    $ git push origin -f main:build     # check results

    # And commit them
    $ git remote update origin
    $ git rebase origin/main
    $ git push origin main:main

**Comment by leamas** [comment]
> I haven't been able to build locally for some time now

To reset whatever state you are in: If you have any uncommitted changes:

    $ git stash

Then, checkout latest known good version:

    $ git remote update origin
    $ git checkout origin/main

Clean up the sources/ directory

    $ git clean -fxd sources

And populate it again

    $ ./source-state.sh restore

build...

    $ antora site.yml

This will always work, without using your changes. To get back to initial state:

    $ git checkout main
    $ git stash pop

**Comment by rgleason** [comment]
Alec the problem is that there are many sequential errors which are show stoppers, so i can never complete what I intended to do. All yesterday I could not complete because of one problem or another, and some were not of my making. Still have not completed.

**Comment by leamas** [comment]
You will complete if you do as I described. Problem then is just that your own modifications will not be part of it. But it should be a starting point

**Comment by rgleason** [comment]
Well the purpose is to update the full manual with the current weather_routing_pi manual changes, not fix everything else.
And doing this will not update weather_routing_pi manual will it?

**Comment by leamas** [comment]
You will get a starting point which works. Without that you're lost.

After coming to this point, you can run `./source-state.sh update`as I have described several times. This will pick upp everything pushed. However, I don't see anything pushed to weather_routing after 26325d739b3ea1cca48249d8ab775ce1d5f73f2b. There are two possible explanations:

  - You havn't rebased  plugins/main, and are thus missing the latest updates
  - You have actually not pushed anything after commit above to weather_routing.

**Comment by rgleason** [comment]
Ok, I tried doing the [process suggested here  ](https://github.com/opencpn-manuals/plugins/issues/31#issuecomment-913098217)and got this result after fixing a conflict and merging and committing.


Rick@Dart MINGW64 ~/documents/github/OM-plugins ((2bba558...))
$ ./source-state.sh restore
fatal: invalid refspec 'eccf43c86d1ee2e2b44bd4c08f9e45371b14848a?'
fatal: invalid refspec '296812e4b5b3b38d9c827527ed86360067af4f35?'
fatal: invalid refspec '6b9416debef44912de2e28c07ad3f732ec732954?'
fatal: invalid refspec 'c6baf5995f3f41bf387536b8572ae1086ac0eee4?'
fatal: invalid refspec '477b21f4113184d0bf516ad453dfc1b292a329ca?'
fatal: invalid refspec 'bc7ec88d12635aaa72a71dea564c798486fb64f0?'
fatal: invalid refspec 'e51c4f7e4815ae24f8e614bcec5bc05e233d0272?'
fatal: invalid refspec '1d914de735db3fbe06d25d43e71dc3b112151ef2?'
fatal: invalid refspec '2ee6b50ee1d7d12f4ce9a439d30f483f3700d9ac?'
fatal: invalid refspec '0befabc46d086a69b6f2ec85a54ba0ee9ad159bc?'
fatal: invalid refspec 'f88efae675945a7f1eb5b3cc33ddaa3ff560d52f?'
fatal: invalid refspec 'f8dc8de594ea8333cb81c18f61fec936019ded94?'
fatal: invalid refspec '9ecccc32896f78ffdf999ee0fcffe289fc85d307?'
fatal: invalid refspec 'f3b96a56762c3d763c00d68b5d5fb3b0a57e4ab3?'
fatal: invalid refspec '79f48e7492ee36421ca746824d1913557176092a?'
fatal: invalid refspec '8763c081cde0cdd8686e9b35c143638d2636a514?'
fatal: invalid refspec '3b0ba7e99ab109523d44076dc0da1e26a141e1de?'
fatal: invalid refspec '6e19a8bfcc8c49cea1f5ddd85c2450b7cf0f33eb?'
fatal: invalid refspec 'ccaf6ffe592eb09a476a1facd8f832975769c90b?'
fatal: invalid refspec '3da698c9b1deb17b28ba28055a7e85c1c53653cf?'
fatal: invalid refspec '605dc3a216a54bae94dd87c68484faa023131586?'
fatal: invalid refspec '693347485d104c4dccd4399295679388d7491cf9?'
fatal: invalid refspec 'd9b355bed47370f4482405ea2b3a6132edc2f683?'
fatal: invalid refspec '693347485d104c4dccd4399295679388d7491cf9?'
fatal: invalid refspec '284bfc902d2e23bbcae691e027121174c92e12e9?'
fatal: invalid refspec '2bf02b72851b1730a5a8a8818a99c69988fb3d57?'
fatal: invalid refspec '9f7882ce7a88c5045d7e0cbbb67951a8093421c9?'
fatal: invalid refspec '404f7eeadf935b1acc1d840f940a6b893f1bdfbc?'
fatal: invalid refspec 'de8239e605b51d01b9c51112b5ebb9833f9e907e?'
fatal: invalid refspec 'd740d429feef982c7b9950cc612c27900141abc9?'
fatal: invalid refspec 'a0553d92bc22421759d4b9938437f6cc8faed596?'
fatal: invalid refspec '5c2f010eb6893a2aa661aea2650330b2c1d42d6f?'
fatal: invalid refspec '1c8e3363fdeb037f1116bba3c1f18635d8e9f025?'
fatal: invalid refspec 'b2c7372a6fcd6841c1e9829704ed31c5fc6874da?'
fatal: invalid refspec '779738508433d912241ffca8e5da24662f9e5460?'
fatal: invalid refspec '582f6f5c263922dc7d80e78e4a08a3c1e226797f?'
fatal: invalid refspec '6a71f40288218aeb4ed3fb839258648a2e8a50dc?'
fatal: invalid refspec 'f28accf6bf7b1754243a170d098cd42c01877eef?'
fatal: invalid refspec '9d2ee9b08e78e9e739f502b827c43583563dbfd4?'
fatal: invalid refspec 'fd03456757c612befe68f7b6e13d80c6d9145a0a?'
fatal: invalid refspec 'daa606f6271c8b521f111f77f8ee655a971e197f?'
fatal: invalid refspec 'e444f72810c92bc176a429be84084610f03e667e?'
fatal: invalid refspec 'afcf2722adb365e45d019fd82b0af99301bd77f0?'
fatal: invalid refspec '1a4da4a89297b49c3264b6129e56e660eec929f0?'
fatal: invalid refspec '8129288df8763c1c1fe0aabeeb2141584a915988?'
fatal: invalid refspec '6eb220ee72efb2221003ac182760c581c147d74d?'
fatal: invalid refspec '3ef00df63027ea317299b213fee33032eaa9efd2?'
fatal: invalid refspec 'f29679c94cc6546af772f1809ca53b6f2efab59d?'
fatal: invalid refspec 'b0b2eb7ac0700232bb2e1b98df7fc5e292c92ca4?'
fatal: invalid refspec '00bc1485a8a02cd696e9f770cafd0a217aa8588c?'
fatal: invalid refspec 'bd928ad74d16b83909f4ef7cfba43ab1d5c6fbc8?'
fatal: invalid refspec 'ca263c8ba42943ca0fda026c4bdd10937fa14144?'
fatal: invalid refspec '26325d739b3ea1cca48249d8ab775ce1d5f73f2b?'
fatal: invalid refspec '08d647a3ddb90fa2c3447670620a454986659321?'

Hope I haven't screwed something up.

**Comment by rgleason** [comment]
I found climatology was not pointing properly when "antora site.yml" locally on my repos.
Then I realized I was working on it and was on branch: master-update  as that is the next one I need to work on.
I have updated & committed that "manual" to "standard arrangement" but it is not the master branch!

**Comment by leamas** [comment]
You certainly don't need another branch. We are three people working on the same thing, and if you keep doing changes on a separate branch you will never be able to make a sane rebase. Stop this, do as I  and Mike and work on the main branch, rebasing it often so it not drifts away.

**Comment by rgleason** [comment]
Alec I was interrupted while working on climatology in a separate branch as I always do whenever possible, in order to make all these manual changes.   That was some time ago.

I am working on each one of my local plugin repositories,  (in the master branch for the most part), merging the PR's from github.com/rgleason  and then making other changes to the manuals.

I am finding that my local repos are generally not caught up with the github counterpart, so I am going through all the PI that are assigned to me and making sure about that.  That is probably where the failures are coming from.

**Make sure your local repositories are caught up to the PR's to your github repos!!!**

**Comment by rgleason** [comment]
Also, there were several plugins that had not had current branches pushed to master, so I am doing that while keeping the manuals dir. as is.  Then I am checking out master.
