### ISSUE TITLE
Still some == top headings

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#33]
There are still some plugins with first heading being == instead of =:

```
sources/GPS-Odometer_pi/manual/modules/ROOT/pages/index.adoc
sources/Deviation_pi/manual/modules/ROOT/pages/index.adoc
sources/ocpn_draw_pi/manual/modules/ROOT/pages/index.adoc

```

**Comment by leamas** [comment]
GPS-odometer fixed in cf4d73d

**Comment by Rasbats** [comment]
@leamas : I have made a PR for ocpn_draw.
[https://github.com/jongough/ocpn_draw_pi/pulls](https://github.com/jongough/ocpn_draw_pi/pulls)

**Comment by leamas** [comment]
@rasbats: Could you please link it here so we can track progress?

**Comment by leamas** [comment]
Deviation_pi fixed in 3866428

**Comment by leamas** [comment]
@rasbats: Seems that the ocpn_draw PR needs an update.  The others are OK

**Comment by Rasbats** [comment]
>Seems that the ocpn_draw PR needs an update. The others are OK

"Edit this page" used an old Rasbats fork of ocpn_draw. This caused a problem because the fork had not been updated. It would have been ok if Jon had made the edit. Might need to add a "gotcha" note somewhere. Authoring?

**Comment by Rasbats** [comment]
ocpn_draw fixed in [https://github.com/jongough/ocpn_draw_pi/commit/693347485d104c4dccd4399295679388d7491cf9](https://github.com/jongough/ocpn_draw_pi/commit/693347485d104c4dccd4399295679388d7491cf9)

**Comment by leamas** [comment]
>  Might need to add a "gotcha" note somewhere. Authoring?

I don't think so, actually. If/when this happens it is a bug that should be fixed rather than documented. Perhaps the best solution is to replace HEAD with 'master'  in site.yml, so we know for sure which branch we are working with. HEAD was convenient in the initial state, but is perhaps not that useful now (?)

**Comment by leamas** [comment]
I'm closing this. The branch issue revealed above needs probably a new issue...

**Comment by rgleason** [comment]
Alec
It might help if the script revealed exactly which plugin it is processing when it is doing antora site.yml to make docs. Otherwise we dont know what pi the errors are from.

**Comment by leamas** [comment]
Yes. Patches welcome...
