### ISSUE TITLE
Remove Google Earth plugin

### ISSUE THREAD

**Issue by Rasbats** [opencpn-manuals/plugins#34]
[https://www.cruisersforum.com/forums/f134/google-earth-plugin-does-not-work-version-5-2-a-240268.html#post3476224](https://www.cruisersforum.com/forums/f134/google-earth-plugin-does-not-work-version-5-2-a-240268.html#post3476224l)

@leamas 
@rgleason 

I am removing this plugin from the manual.

**Comment by leamas** [comment]
Right, please just do it. I filed a bug against the gtihub repo: https://github.com/nohal/gecomapi_pi/issues/8

**Comment by leamas** [comment]
Seems fixed in c55433e. Time to close?

**Comment by Rasbats** [comment]
Closing.
