### ISSUE TITLE
opencpn-manuals/plugins

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#36]
Was not on the main branch   the head was somewhere else.
git checkout main
git pull
It fast forwards.

```
Fast-forward
 manual/master-plugins/modules/ROOT/pages/plugins.adoc        | 4 ++--     <-- found plugins.adoc
 manual/master-plugins/modules/ROOT/partials/nav-plugins.adoc | 4 ++--   <-- Found nav-plugins.adoc
 site.yml                                                     | 3 ++-
 sources.state                                                | 5 ++---
 4 files changed, 8 insertions(+), 8 deletions(-)

```

**Comment by rgleason** [comment]
When I try to "clone all the required sources I get this

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$  ./source-state.sh restore
fatal: invalid refspec 'eccf43c86d1ee2e2b44bd4c08f9e45371b14848a?'
fatal: invalid refspec '296812e4b5b3b38d9c827527ed86360067af4f35?'

and so on.
```

When I try 

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
error: antora.yml not found in C:\Users\Rick\documents\github\OM-plugins\sources\watchdog_pi\ (ref: HEAD <worktree> | path: manual)
Add the --stacktrace option to see the cause.

```

What is missing?

**Comment by rgleason** [comment]
Then I tried

$ git remote update origin
$ git rebase origin/main
which worked, then
$ ./source-state.sh update.
..and there is a long list.  It was too long, so I tried it again making an output.txt file


```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ ./source-state.sh update >output.txt
HEAD is now at eccf43c Update index.adoc fix headings "=="
HEAD is now at 296812e Merge pull request #4 from opencpn-manuals/manual-pr
HEAD is now at 6b9416d Update.adoc fix headings "=="
HEAD is now at ed3b846 Merge pull request #5 from rgleason/frontend2
HEAD is now at 477b21f Merge pull request #3 from opencpn-manuals/manual-pr
HEAD is now at bc7ec88 Update index.adoc
HEAD is now at e51c4f7 Merge pull request #13 from Rasbats/patch-1
HEAD is now at 1d914de Merge branch 'master' of https://github.com/rgleason/chartscale_pi
HEAD is now at 4b46e50 manual merging
HEAD is now at 0befabc index.adoc: Fix == top heading level.
HEAD is now at f88efae Update index.adoc
HEAD is now at f8dc8de ==
HEAD is now at 9ecccc3 drop some dokuwiki leftovers
HEAD is now at f34511b manual smll changes
HEAD is now at f5d6069 Add note about discontinuation of the project
HEAD is now at 79f48e7 index.adoc: Adjust heading level (#26).
HEAD is now at 8763c08 Merge pull request #20 from opencpn-manuals/manual-pr
HEAD is now at 3b0ba7e Merge pull request #9 from opencpn-manuals/manual-pr
HEAD is now at ed0f135 manual sml chngs
HEAD is now at ccaf6ff Update index.adoc
HEAD is now at 3da698c handle attachments, add a gitignore
HEAD is now at 605dc3a Merge pull request #11 from oplaydo/master
HEAD is now at d9b355b Merge pull request #7 from opencpn-manuals/manual-pr
HEAD is now at 6933474 Merge pull request #481 from Rasbats/master
HEAD is now at 284bfc9 Merge pull request #123 from opencpn-manuals/manual-pr
HEAD is now at 2bf02b7 ==
HEAD is now at 9f7882c ==
HEAD is now at 404f7ee ==
HEAD is now at de8239e ==
HEAD is now at eb4a268 manual small chngs
HEAD is now at ca586ee manual improvements
HEAD is now at 5c2f010 Update index.adoc  fix headings "=="
HEAD is now at 9519feb manual improvements
HEAD is now at b2c7372 manual: Use Antora defaults: race-start.adoc -> index.adoc.
HEAD is now at 7797385 Merge pull request #177 from opencpn-manuals/manual-pr
HEAD is now at 7f266a3 manual improvements
HEAD is now at 6a71f40 Merge pull request #3 from leamas/patch-1
HEAD is now at 1f00d7d manual sml chngs
HEAD is now at 9d2ee9b Merge pull request #25 from opencpn-manuals/manual-pr
HEAD is now at fd03456 ==
HEAD is now at daa606f ==
HEAD is now at e444f72 ==
HEAD is now at 96f3f63 manual sml chngs
HEAD is now at 1a4da4a ==
HEAD is now at 46d9e0f manual - sml chng
HEAD is now at 6eb220e ==
HEAD is now at 3ef00df index.adoc: Adjust heading level (#26).
HEAD is now at f29679c ==
HEAD is now at 4893395 manual chngs
HEAD is now at 00bc148 ==
HEAD is now at 1306a7d manual sml change
HEAD is now at fef0dcc manual-changes
HEAD is now at 001181e manual sml chngs
HEAD is now at 08d647a Update manual
```

Did that finish properly?   (This list is different than the one belore)
I see a lot of my commits here.

**Comment by rgleason** [comment]
```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ antora site.yml
asciidoctor: ERROR: index.adoc: line 7: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: index.adoc: line 33: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: index.adoc: line 148: level 0 sections can only be used when doctype is book

```

I am not at all sure which plugin or index.adoc this is or where it is located!  
Better reporting is required here.

**Comment by rgleason** [comment]
To view as html   file:///C:/Users/Rick/Documents/GitHub/OM-plugins/docs/opencpn-plugins/0.1/index.html
Reviewed the plugins  I had changed and saw that they were updated. Theere are more things to fix.

To push this and make a new build:
$ git add sources.state
$ git commit -m "Update sources to latest versions"
$ git push -f  origin main:build

Did this and 
Nothing was added to commit

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git push -f origin main:build
Everything up-to-date
```

**Comment by rgleason** [comment]
If everything looks sane, push also to main:

$ git remote update origin
$ git rebase origin/main
$ git push origin main:main

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git push origin main:main
Everything up-to-date

```

So I guess it is working.

**Comment by leamas** [comment]
> I am not at all sure which plugin or index.adoc this is or where it is located!
Better reporting is required here.

Indeed. Patches welcome.

These things happens because you don't stick to the general rule to commit small changes. If you change a single repo at a time and commit you know the culprit if there are any problems.

Some simple include/omit in sute.yml reveals that the first two errors are from admiralty_tide_tables and the third from Deviation. Seems that you have multiple level 0 headings which confuses Antora.

**Comment by leamas** [comment]
> Nothing was added to commit

As described multiple times: after updating sources.state you must also update sources. That is, the complete cycle toi make a new build after new commits in opencpn-manuals/plugins is

    $ git remote update origin
    $ git rebase origin/main
    $ ./source-state-.sh restore
    $ antora site.yml

If you omit the last step the sources/ directory will still be the same, and you don't see the changes you have done

**Comment by leamas** [comment]
> When I clone i get
$  ./source-state.sh restore
fatal: invalid refspec 'eccf43c86d1ee2e2b44bd4c08f9e45371b14848a?'


These things happens if you have changed the upstream repo, for example moved it to someone else. The simple solution in these cases is to remove the directory under sources/ an run ./source-state.sh restore again. You need to find which repo it is about by looking for the commit  in source-state.sh.

If in doubt, just remove everything under sources (besides .gitkeep) and re-run ./source-state.sh restore. It takes some time, but is reasonably safe.

**Comment by leamas** [comment]
You have by the way not changed sources.state in any of the commands described above. Hence the 'Everything is up to date' messages which basically says that there is nothing to commit or push.

**Comment by rgleason** [comment]
Ok, there is a lot here.

`Some simple include/omit in sute.yml reveals that the first two errors are from admiralty_tide_tables and the third from Deviation. Seems that you have multiple level 0 headings which confuses Antora.`

I will check admiralty, deviation is not mine.

I did not run antora site.yml the last time.  I guess it is necessary.
More later. Thanks.

**Comment by rgleason** [comment]
Have fixed  admiralty_tides_table  0 headings and update nav.adoc s with a commit.

Now find this one

```
./Findit_pi: Fetching origin
error: Your local changes to the following files would be overwritten by checkout:
        manual/antora.yml
        manual/site.yml
Please commit your changes or stash them before you switch branches.
Aborting
./gecomapi_pi: Fetching origin
```

Don''t quite know how to fix it. I already pushed the commit.

**Comment by rgleason** [comment]
Now get this after fixing some other things.


```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ antora site.yml
asciidoctor: ERROR: index.adoc: line 148: level 0 sections can only be used when doctype is book
```

You say it is from Deviation, how did you learn this?  II will try to fix it tomorrow.

**Comment by leamas** [comment]
I confirm this by excluding (commenting out) it in site.yml, and see the error go away when running _antora site.yml_.

Of course, the list of plugins is long, so one need to organize the search. From the beginning, I commented out half of the plugin list. Depending on if error go away when using this, I know which half of the list which contains the culprit. I  then comment half of this and goes on.  It takes 5 rounds to find any plugin this way, which goes quite fast.

Again: this doesn't happen if we merge changes one by one. If we update one plugin and get new errors there is no need to search. This is how we should work to avoid these kind of searches

**Comment by leamas** [comment]
The simple way to check is otherwise to rebuild the Deviation manual in sources/: 

    $ cd sources/Deviation_pi/manual
    $ antora  site.yml
    asciidoctor: ERROR: index.adoc: line 148: level 0 sections can only be used when doctype is book

This also means one should avoid these kind of errors by doing a local build **of the plugin** before pushing changes. If you had done this, there would have been no need to search for failing plugins in opencpn-plugins/plugins

**Comment by leamas** [comment]
@rasbats @rgleason 

I have added a new script check-sources. It rebuilds all manuals in _sources_, making it easier to find a plugin which generates errors in the overall build.

**Comment by leamas** [comment]
Here an excerpt from the output from check-sources, IMHO it basically says everything:

```
==== Building plugins/sources/admiralty_tide_tables_pi/manual/site.yml
asciidoctor: ERROR: index.adoc: line 8: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: index.adoc: line 34: level 0 sections can only be used when doctype is book
asciidoctor: WARNING: dashboard.adoc: line 356: invalid style for paragraph: NmeaConverter_pi
No manual/site.yml found in /home/mk/src/opencpn-manuals/plugins/sources/aisradar_pi
==== Building plugins/sources/Autopilot-Plugin/manual/site.yml
==== Building plugins/sources/autopilot_route_pi/manual/site.yml
==== Building plugins/sources/AutoTrackRaymarine_pi/manual/site.yml
==== Building plugins/sources/calculator_pi/manual/site.yml
==== Building plugins/sources/celestial_navigation_pi/manual/site.yml
==== Building plugins/sources/chartscale_pi/manual/site.yml
==== Building plugins/sources/climatology_pi/manual/site.yml
==== Building plugins/sources/Deviation_pi/manual/site.yml
asciidoctor: ERROR: index.adoc: line 148: level 0 sections can only be used when doctype is book
==== Building plugins/sources/DR_pi/manual/site.yml
==== Building plugins/sources/EarthExplorer_pi/manual/site.yml
==== Building plugins/sources/EngineDashboard/manual/site.yml
==== Building plugins/sources/Findit_pi/manual/site.yml
==== Building plugins/sources/gecomapi_pi/manual/site.yml
==== Building plugins/sources/GPS-Odometer_pi/manual/site.yml
==== Building plugins/sources/iacfleet_pi/manual/site.yml
==== Building plugins/sources/launcher_pi/manual/site.yml
==== Building plugins/sources/LogbookKonni_pi/manual/site.yml
==== Building plugins/sources/ncdf_pi/manual/site.yml
==== Building plugins/sources/NmeaConverter_pi/manual/site.yml
No manual/site.yml found in /home/mk/src/opencpn-manuals/plugins/sources/objsearch_pi
==== Building plugins/sources/ocpndebugger_pi/manual/site.yml
==== Building plugins/sources/ocpn_draw_pi/manual/site.yml

```

**Comment by Rasbats** [comment]
@leamas : Thanks. check-sources is a good addition.

**Comment by rgleason** [comment]
@leamas 
You wrote above:
`
...f errors by doing a local build of the plugin before pushing changes. If you had done this, there would have been no need to search for failing plugins in opencpn-plugins/plugins`

Please NOTE: Deviation is not my plugin, it is Dirk's. I do not have control of it.

**Comment by leamas** [comment]
> Please NOTE: Deviation is not my plugin, it is Dirk's. I do not have control of it.

It's not Dirks, not yet, site.yml still points to the fork in opencpn-manuals (see #23).   You have full write access to this fork.

Anyway, I have updated the fork.  The PR at https://github.com/RooieDirk/Deviation_pi/pull/12 is also updated. This was actually my bad, so it makes sense that I fix it :)
