### ISSUE TITLE
source-state.sh Error

### ISSUE THREAD

**Issue by Rasbats** [opencpn-manuals/plugins#37]
Changing branch: HEAD to branch: master has caused problems with source-state.sh. This problem with restore:

```
fatal: invalid refspec '9038e864911f269d6a376b21740f1782f7b322c5?'
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
```

**Comment by leamas** [comment]
Just remove the directories under sources and re-run source-state.sh, this  should fix this. 

This time, leave .gitkeep in place...

**Comment by Rasbats** [comment]
Thanks. That works!

**Comment by leamas** [comment]
Yup. This is basically the big and clumsy hammer which should fix any problems with restore as long as sources.state is sound.

**Comment by Rasbats** [comment]
While you are here I need to use sqlite in my ais app:
[https://github.com/Rasbats/aisRX](https://github.com/Rasbats/aisRX)
This plugin uses the ShipDriver template.
objsearch_pi has a template but is not a managed plugin. I have not been able to find other examples.
aisRX needs to access the EU River Information Services database, This is now an sqlite file.
Will raise an issue in the aisRX repo.

**Comment by leamas** [comment]
OK. Just file issue(s) in your plugin repo(s) and drop me a note...
