### ISSUE TITLE
Generated files in repo

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#4]
Having generated files in the repository is frowned upon for many reasons. One is a sheer size issue: The current plugins repo is about 300 MB. Of these, the generated html files are roughly 100 MB, and the sources directory also around 100 MB. All in all two thirds of the repo consists of things which IMHO just shouldn't be here.

IMHO, we should:

  - Drop the generated html files, using the setup from main repo
  - Drop the files under sources, using the source-state.sh scripts instead; also like in main repo

BTW: There is also about 100MB in the .git repo, so if we drop things according to above a shallow clone should just be a few MB as compared to 300...

**Comment by leamas** [comment]
I could help here, but will not touch anything until we have talked.

**Comment by Rasbats** [comment]
I will let you work on this one until told otherwise, to avoid a clash. 

>Drop the files under sources, using the source-state.sh scripts instead; also like in main repo

This would be good. Not sure how this works with a local build of plugins. Run script locally and then build locally?

**Comment by leamas** [comment]
> This would be good. Not sure how this works with a local build of plugins. Run script locally and then build locally?

Two things: First, add sources to .gitignore.

Second: The work cycle:
    - Run `./source-state.sh restore`. This will populate sources/ using commits and urls stored in sources.state.
    - Do local builds.
    - Occasionally, you might want to update sources/. One way is to run `./source-state.sh update` which will fetch latest available commit in each directory. 
    - Or, you could update a single repo using `cd sources/a_plugin; git pull origin master` or so.
    - After updating any of the directory in sources: run `./source-state.sh save`. This updates sources.state so it reflects what you actually have in sources. Commit this change. This way next user which clones your repo (probably the ga builder) will have the same set of plugins as you after running `./source-state.sh restore`

**Comment by leamas** [comment]
BTW: The hairy stuff here is to keep sources.state and sources/ in sync. There is an obvious risk that a dev like me updates  sources/ somehow without doing a ./source-state.sh save. This means that when someone else clones the repo, sources/ will be different compared to what I used.

It might make sense to add a check that sources.state reflects sources/ to the pre-commit hook...

**Comment by Rasbats** [comment]
Why not add save to ./source-state.sh update? Don't we need the latest from devs repos?

**Comment by leamas** [comment]
Perhaps a good idea, dunno. The argument against is that save is still necessary if you update anything by other means like updating a single plugin (or perhaps removes/adds one). 

OTOH, an automatic test would always be consistent. Not saying you are wrong, just thinking aloud.

**Comment by leamas** [comment]
BTW: no, we don't always need the latest. On the contrary, in the end of the release cycle we want things to be more stable and only import changes which we need to fix bugs. Yes, it's like programming...

**Comment by rgleason** [comment]
Guys, I follow some of this, but I think we should have a Author's Manual with instructions on use, as the process changes extemporaneously.  It would be best to follow that rather than the wrong Issues.

**Comment by leamas** [comment]
@rasbats: I have worked a little with the ci script aimed to build the results. To that end, I have also meddled with Settings | Pages in the plugins project. Hope it's ok.

Have pushed my work onto the ci branch. It contains a lot of bugfixes, but there is some left which makes the results unusable (it doesn't find any index.html). Do whatever you like with those commits; one alternative is to merge them.

Note the command to trigger a build: `git push -f origin ci:gh-pages`from ci branch, or otherwise from main `git push -f origin main:gh-pages`

**Comment by leamas** [comment]
@rgleason : No point making docs before the workflows have stabilized. And, they have not.

Crash course for the development manual. To initiate a build and publish the results, assuming you have worked on the main branch: `git push -f origin main:gh-pages`. This is a fast build, the result are published on https://opencpn-manuals.github.io/development/.

There is no need to use the main branch. When testing things you can create a new branch foo, put some commit s on it and do `git push -f origin foo:gh-pages`. The results will be available on the same location, overwriting whatever was there.

**Comment by Rasbats** [comment]
>To that end, I have also meddled with Settings | Pages in the plugins project. Hope it's ok.

:) Ok. No docs in the repo but it does build locally for me.

**Comment by leamas** [comment]
>  No docs in the repo 

:( 
> but it does build locally for me.

same here

**Comment by Rasbats** [comment]
Main builds but not ci. Not finding a source.
Need to add sources using the script and try again!

**Comment by leamas** [comment]
Let  me have a look...

**Comment by leamas** [comment]
@rasbats: ci branch at 4c840f61 builds for me (i. e., antora site.yml).

Have you refreshed your sources before building? To be really sure: ` rm -rf sources/*; ./source-state.sh restore`. I did it (painfully slow...) and it worked for me.

**Comment by rgleason** [comment]
Github move issues feature
https://www.google.com/search?client=firefox-b-1-m&sxsrf=ALeKk00JySG408iIU1REGKQnjqdSV6vTlw%3A1628528517631&q=github+move+issues+feature&oq=github+move+issues+feature&aqs=heirloom-srp..

**Comment by Rasbats** [comment]
Getting multiple "cannot checkout" errors, working locally with the ci branch and using ./source-state.sh restore. 
dashboard_tactics_pi is an example. I need to check if the commit in sources.state matches the dev repo commit.

**Comment by leamas** [comment]
@rgleason : just do it.

**Comment by leamas** [comment]
@rasbats
> Getting multiple "cannot checkout" errors, working locally with the ci branch and using ./source-state.sh restore

Weird.  Can you run these and submit the output?

```
$ git diff sources.state
$ git diff --staged sources.state
$ git log --oneline -1 sources.state

```

**Comment by Rasbats** [comment]
Ricks repo for dashboard_tactics_pi no longer has the manual in it!!!
I will need to check for those repos with "cannot checkout errors".

>Weird. Can you run these and submit the output?

Ok.

**Comment by Rasbats** [comment]
```
Mike@vostro-64 MINGW64 /c/Projects/opencpn-manuals/plugins (ci)
$ git log --oneline -1 sources.state
13558be move to main iso manual

```

**Comment by leamas** [comment]
Assuming the diff commands did not return anything this means that you and I have identical sources.state. 

Which means that the contents in sources/ is the suspect.  Have you removed all directories under sources/ before running restore?

**Comment by Rasbats** [comment]
Yes.

**Comment by Rasbats** [comment]
Example of error:

```
fatal: invalid refspec 'a23a2793d7a9c5282b5e22c0f3b070049f90fe51?'
Error: ./TideFinder_pi: Cannot check out commit a23a2793d7a9c5282b5e22c0f3b07004
```

**Comment by Rasbats** [comment]
Going for  a meal!

**Comment by leamas** [comment]
still, it works for me... What does `git --version` say for you? (I'm on 2.30.2)

I can print that object, in  the TideFInder dir: 

```
$  git cat-file -p a23a2793d7a9c5282b5e22c0f3b070049f90fe51
tree 98644dbd3942bb894f74a06819b26fe76c1b85f5
parent b9eae394bd9f74651afb1ce5e93cd65ca33f48bd
author Rasbats <miker@members.swis.net> 1619601558 +0100
committer Rasbats <miker@members.swis.net> 1619601558 +0100

Add manual

```

**Comment by leamas** [comment]
I did have such problems when cloning plugins before you renamed the manual directory to 'manual'.  It was git sparse-checkout which didn't include the required objects due to wrong paths. Same here, somehow?

You could try to edit the source-state.sh script to just use regular checkout. Any difference?

**Comment by Rasbats** [comment]
```
$ git --version
git version 2.32.0.windows.2
```

**Comment by leamas** [comment]
hm... could it be that difference? git sparse-checkout is documented as unstable, so anything is possible.

Can you edit the script to use regular checkout instead? Something like

```
--- a/source-state.sh
+++ b/source-state.sh
@@ -31,7 +31,7 @@ cleanup_clone() {
 
 git_clone() {
     vers=$(git --version)
-    if [[ "$vers" == *2.[345][0-9].* ]]; then   # > 2.30
+    if [[ "$vers" == *8.[345][0-9].* ]]; then   # > 2.30
         git clone --depth 1 --filter=blob:none --sparse $1
         cd $2
         git sparse-checkout set manual antora.yml modules
```

**Comment by rgleason** [comment]
@leamas  "just do it"
You mean just go ahead and move the issues?  -i am just a bit nervous dont want to screw it up, but will try later today.

@Rasbats  dont know what happened w dashboard tactics will check.

**Comment by Rasbats** [comment]
I think the problem with ci is github desktop. Now using command line and so far so good. Report back later.

**Comment by Rasbats** [comment]
ci is now building locally. No changes to source.state.sh or anything else in ci.

**Comment by Rasbats** [comment]
@rgleason : It is ok Rick. The commit for dashboard_tactics_pi is not in the main branch. It's in fe.... and the script found the manual there.

**Comment by rgleason** [comment]
@Rasbats
Thanks, there is also a "doc" folder in master to Petri's documentation which is not using asciidoc/antora but  "readthedocs" and the other system. 
Not sure what we should do to straighten this out, but I could make a git -m master.old branch and then find the other branch to make it master.

**Comment by Rasbats** [comment]
Best to leave as is at the moment. It works.

**Comment by leamas** [comment]
@rasbats: great. I was kind of confused until you found the error.

Command line rules! At least when handling git.

I still wonder why the published site don't work. The setups in main and development are more or less the same, and works just fine. Problem is that is is so utterly hard to debug the action modules for checkout, antora, publish etc. We'll find the problem eventually

**Comment by leamas** [comment]
> Best to leave as is at the moment. It works.

One point here is that as long you don't update sources.state  it doesn't matter whatever changes Rick pushes -- you will still get current version. We indeed do not want the latest in all situations

I have been thinking about adding some kind of "lock" in source-state.sh.  The idea is that it should be possinbe to lock a repo to so an update operation does not affect it.

**Comment by leamas** [comment]
@rasbats: We need to finish our work here. We have the playdo branch and the ci update. Is it OK if I merge these into main?

**Comment by Rasbats** [comment]
Yes ... please merge.

**Comment by leamas** [comment]
Done. I have dropped the ci branch. It would be great if you dropped the playdo branch, it's your baby. Kill using `git push origin :playdo`

**Comment by leamas** [comment]
From this point it's important to verify that things we pushes actually builds. I work like this:

    $ checkout -b testing-stuff
    $ # commit all sorts of things on testing-stuff
    $ git push -f testing-stuff:build  # Check that build is OK
  
As long as the build  runs without errors, I  consider the branch sane. To finally merge:

    $ git remote update origin
    $ git rebase origin/main    # fix possible conflicts
    $ git checkout main
    $ git merge testing-stuff
    $ git push origin main:main

**Comment by leamas** [comment]
Time to close this bug? The ci job ensures that we always can rebuild form fresh sources.

**Comment by leamas** [comment]
Yes, lets's close. There is no generated stuff checked in
