### ISSUE TITLE
sources.state: Unordered -> strange diffs.

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#41]
The sources.state file is supposed to be sorted. By keeping this simple rule, diffs becomes sane and reasonably easy to review.

`./source-state.sh save` does ensure that sources.state is sorted correctly.

However, as of current HEAD at 52eac3a sources.state is not sorted. In this particular case, this seems to come from abb633da2, but I have noticed this before.

Will try to resort the file, PR under way.

Proposed workflow after manually changing anything besides a plain commit hash in sources.state:

    $ ./source-state.sh restore                            # Make sure everything is sane
    $ ./source-state.sh save                                # Save a correct, sorted sources.state.
    $ git commit -am  "sources.state: why it was changed"

**Comment by leamas** [comment]
Hopefully fixed in 4c309e9

**Comment by leamas** [comment]
Leaving open for some time as a heads-up.

**Comment by Rasbats** [comment]
Used:
$ ./source-state.sh update                           # to bring everything up to date
$ ./source-state.sh save 

The commit did not seem to change the order in sources.state. ?????

**Comment by leamas** [comment]
If you dit it on currrent main at 6f15c0c465 it is because I have sorted it ?

**Comment by leamas** [comment]
How it works could be shown by going back in time:

    $ git checkout 52eac3a    # checkout the version I complained about in this bug.
    $ ./source-state.sh restore
    $ ./source-state.sh save
    $ git diff

... and it's clearly visible how `save`creates a sorted sources.state.

**Comment by Rasbats** [comment]
The commit made with update/save was [https://github.com/opencpn-manuals/plugins/commit/abb633da21d74a94b0008f68dfe7f15d135dd750](https://github.com/opencpn-manuals/plugins/commit/abb633da21d74a94b0008f68dfe7f15d135dd750)
It seems that using update/save without a restore caused the problem ???

**Comment by leamas** [comment]
Well, the overall rule is to keep the file sorted. Using `./source-state.sh save` does this, but in order to save the correct commits  (which save fetches from _sources/*_) one need to run  `./source-state.sh restore`  first.

OTOH, many changes are just about modifying a commit hash, and does not change ordering.

And some of us are using editors where one can mark an area and pipe it through an external command like _sort_, that what was I did here to clean up. Anything goes, as long as the file is sorted.

**Comment by leamas** [comment]
BTW: The command line oneliner (untested) to sort should be 

    $ sort sources.state > sources.state.tmp && cp sources.state.tmp  sources.state && rm sources.state.tmp

**Comment by Rasbats** [comment]
> which save fetches from sources/*

I was using an empty sources/* directory for most commits previously. Only used` ./source-state.sh restore` when I made a local build yesterday.

Could` $ sort sources.state > sources.state.tmp && cp sources.state.tmp  sources.state && rm sources.state.tmp`
be incorporated in ` ./source-state.sh update`?

**Comment by leamas** [comment]
Anything is possible, but that does not make much sense since _update_ doesn't update sources.state, just sources/.

Actually, the semantics are quite simple, and it might wise to stck to them:

  - _restore_ copies state from sources.state -> sources
  - _update_ updates sources
  - _save_ copies state from sources -> sources.state

This is actually quite simple (?). Anything which goes beyond this might make things even harder to understand.

Perhaps we could add a new command  _./source-state.sh sort_ which sorts sources.state if that would be useful, it is at least well defined ?

**Comment by leamas** [comment]
>  was using an empty sources/* directory for most commits previously.

That is probably a bad idea. Running _./source-state.sh restore_ is a simple way to make sure that changes are sane before they are committed. It could even be argued it should be part of a pre-commit hook...

EDIT: While running _restore_ on an empty sources directory is slow, doing the same thing with sources in place goes reasonably fast.

**Comment by Rasbats** [comment]
> update updates sources

I had forgotten that. Make note to self.

**Comment by leamas** [comment]
The thing is that one could all sorts of things with sources before running _save_. Adding a new source, remove an existing, checkout a new commit in the sources/foo repo and run a test build. In any case, _save_ will create a correct sources.state file which reflects what's in sources.

Also note that from now it is possible to update just a single plugin (./source-state.sh update plugin) before running save which creates simple, clean commits.

**Comment by leamas** [comment]
@rasbats: The problem is that your list is sorted case-sensitive; in other places it has been done insensitive. Does _./source-state.sh save_ create the ordering in 076cb21 on Windows?

**Comment by Rasbats** [comment]
Yes ... save did create the ordering in https://github.com/opencpn-manuals/plugins/commit/076cb215ca7fb5bd2767d41267c48691f3e5c958

**Comment by Rasbats** [comment]
Are we into a Windows thing here?

**Comment by rgleason** [comment]
Well, it could be called a linux thing too.

**Comment by leamas** [comment]
Anyway, I will push a fix for this. I'll also resort sources.state. Stay tuned.

**Comment by leamas** [comment]
Done: New HEAD: c20e7d1.   Sources.state re-sorted, source-state.sh patched to always use case-insensitive sorting.

That is, I think so, havn't checked on Windows. Could perhaps someone...

**Comment by Rasbats** [comment]
Yes ... I am going for it.

**Comment by Rasbats** [comment]
commit db568938d9c3f20b2f1103cbb738f8961c572dde looks good.

**Comment by leamas** [comment]
OK, we can pout that aside then. Thanks!

**Comment by leamas** [comment]
Let's close this, I think we have finally sorted (pun intended) this out.
