### ISSUE TITLE
Does  Edit this page work with Internal Plugins?

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#48]
Dashboard
https://github.com/opencpn-manuals/plugins/commit/4ec705327b70de5d7e89784a481f3ef4ebbc3b9d

These changes did not show up, did not find them on  https://github.com/OpenCPN/OpenCPN/pulls  one to fix a bad link

* Source: https://github.com/OpenCPN/OpenCPN/tree/master/plugins[]
* Forum: http://www.cruisersforum.com/forums/f134/plugin-dashboard-44087.html[Forum Discussion thread]
* Companion Plugin: xref:nmea_converter::index.adoc[Nmea_Converter_pi] can solve many conversion problems.

**Comment by rgleason** [comment]
Actually,  after  getting current locally, 
I see the three link changes and reformatting  is there in main

https://github.com/opencpn-manuals/plugins/commit/4ec705327b70de5d7e89784a481f3ef4ebbc3b9d

Therefore knowing what I know now, I believe the "Edit this Page" can be kept on the Internal Plugins.

**Comment by rgleason** [comment]
You can close if you agree.

**Comment by leamas** [comment]
The Edit This page is not really about plugins in this case. There is no separate git repo for these, they are part of the overall opencpn-manuals/plugins repo. We could enable this page here or not, that is another issue.

Again: I think it could be good to keep the link available. However, if one is to merge these PR:s one must understand how the overall workflows in opencpn-manuals/plugins which is not trivial.

**Comment by rgleason** [comment]
So I guess we 3 just stay away from "Edit this page"  when in opencpn-manuals/plugiins
