### ISSUE TITLE
plugins repo is not cloned by source-state.sh

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#5]
When source-state.sh makes a sparse checkout of the plugins project, it won't include the subdirectory *plugins* which contains the manual stuff.

This could be attacked in the source-state.sh script or in the plugins project. As for source-state.sh, I have updated it to clone the default antora paths *antora.yml* and *modules* besides the common *manual*.  A simple fix would be to add *plugins* to this list. However, my gut feeling is not great about this. To have a limited set of directories manual, antora.yml and modules seems sound to me.

Given this, would it be possible to rename the plugins subdirectory, currently plugins/plugins to plugins/manual? This would keep us all adhering to the same scheme which I think could be good.

Thoughts?

**Comment by Rasbats** [comment]
Will rename plugins/plugins to plugins/manual. At the same time I would like to change manual and manual-beta, presently in the plugins folder. Thinking master-plugins and beta-plugins. Does this cause a problem?

**Comment by leamas** [comment]
No. The sparse checkout will take everything under manuals/, whatever files/dirs there are.

EDIT: "no" in the sense "no problem" :)

**Comment by Rasbats** [comment]
Done. plugins repo builds fine standalone.

**Comment by leamas** [comment]
Done in main repo, rebuilt (will push ASAP). Thanks!

**Comment by leamas** [comment]
Pushed to main [tip](https://github.com/opencpn-manuals/main/commit/f0b16818fcc5e1225eb53122cd6f889fbaaeacc7). Closing.
