### ISSUE TITLE
Squiddio  PR accepted by Mauro  not listed in sources-state

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#50]
add squiddio line

**Comment by leamas** [comment]
Nor is it listed in site.yml...

**Comment by rgleason** [comment]
I guess someone has to add those after getting current?
Is that me?  Or should I leave that to others for the time being?

**Comment by leamas** [comment]
Fixed in 368349d

**Comment by rgleason** [comment]
Thanks
