### ISSUE TITLE
Manual changes PR merged, not showing in opencpn-manuals/plugin 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#51]
For example, I made changes to douwe's autotrackraymarine plugin and the PR was merged 6 hours ago.
However I have,  see https://github.com/opencpn-manuals/plugins/pull/44#issuecomment-921156816 

$ git remote update origin
$ git rebase origin/main
$ ./source-state.sh update
$ git rev-parse --short HEAD    db56893
$ check-sources
$ antora site.yml

Am I missing something here?
Why aren't the changes to autotrackraymarine showing?

**Comment by leamas** [comment]
See https://github.com/opencpn-manuals/plugins/pull/44#issuecomment-921091752

**Comment by rgleason** [comment]
Builds SHA has gone up.... closing.
You have to keep checking I guess.
