### ISSUE TITLE
Changing site.yml and antora.yml with in the opencpn-manuals/plugin  Plugins

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#52]
You moved the locations for plugins awaiting merges out of sources I think. I just found them above opencpn-manuals/plugins
in opencpn-manuals.   

Later, I am going to have to git clone opencpn-manuals I guess, but I would like to simply edit these plugins in opencpn-manuals, for two very simple changes to site.yml and antora.yml  "titles"

1.  Nmea Converter
2. AISradar
3. Deviation
4. GPS-odometer
5. oernc 

However that process results in a PR and requires a merge.
Additionally, when I have been forking plugins and starting to make these small changes I am given a choice of forkiing to rgleason or opencpn-manuals.    Should I be selecting "opencpn-manuals?  I have been selecting rgleason.

Can I simple edit these files on line and make a PR to the source repository?  It will be much easier.

**Comment by leamas** [comment]
My note about linear history (and thus to avoid merges) was about opencpn-manuals/plugins. As for the individual plugins mentioned here just go on, edit on.line and make your PRs

If you fork into opencpn-manuals all of us (Mike, me and you) can make changes in the PR. If you fork to your own user only you can make changes. The ability to amend a PR is important. For example: GPS-Odometer is forked into opencpn-manuals, so you could have amended the PR rather that writing email to Lennart about various, detailed edits to be done.

**Comment by leamas** [comment]
BTW: I have amended the GPS-Odometer PR, so your email is sort of unnecessary.

**Comment by rgleason** [comment]
`If you fork into opencpn-manuals all of us (Mike, me and you) can make changes in the PR. `

Good Point, this is part of learning the best way to use this system.
Should I then try to clone all of  opencpn-manuals   (including plugin repos and development repos) ?
Don't we have to clone these repos locally and then push them up to opencpn-manuals??
Maybe I should just try it when the prompt comes up and see what happens.

**Comment by rgleason** [comment]
`Can I simply edit these files on line and make a PR to the source repository? It will be much easier.`

So the answer is Yes

**Comment by rgleason** [comment]
These were edited and not yet  accepted.
Nmea Converter -yes
AISradar  - waiting
Deviation - yes?
GPS-odometer - yes?

Closing
