### ISSUE TITLE
[full-linkcheck]  did not work and admiralty errors too

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#53]
https://github.com/opencpn-manuals/plugins/actions

```
+ antora site.yml
error: Local content source does not exist: /home/runner/work/plugins/plugins/sources/admiralty_tide_tables_pi (url: sources/admiralty_tide_tables_pi)
Add the --stacktrace option to see the cause.
Error: Process completed with exit code 1.
```

Have to find out what changed.

**Comment by rgleason** [comment]
Tried again and it worked.  Did not have any change really.  I did try to find something wrong in admiralty and generated antora site.yml successfully but there were no commits needed.

https://github.com/opencpn-manuals/plugins/runs/3628274322?check_suite_focus=true

Did this

```
$ git remote update origin
$ git rebase origin/main
$ ./source-state.sh restore   -to check if pi have been added.
$ ./source-state.sh update    -several times.
$ git rev-parse --short HEAD 
$ check-sources
$ git rev-parse --short HEAD   7f1c991 
$ antora site.yml

Review changes in html at file:///C:/Users/Rick/Documents/GitHub/OM-plugins/docs/opencpn-plugins

$ ./source-state.sh save
$ git status
$ git add site.yml
$ git add sources.state
$ git commit -m "Update sources to latest version"
$ git push -f origin main:build

Look around, if everything looks sane, then push also to main:
What is sane? what should I do?

$ git remote update origin
$ git rebase origin/main
$ git push origin main:main
$ git commit -m "[full-linkcheck] empty commit" --allow-empty
     [main 7f1c991] [full-linkcheck] empty commit

Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git commit -m "[full-linkcheck] empty commit" --allow-empty
[main 2c73c1b] [full-linkcheck] empty commit

```

**Comment by rgleason** [comment]
There are some fixes needed.

- unresolved antora refs
- autopilot_route   links
- weather_routing/ links

-nothing else found

weatherfax needs   gitignore  docs!!!

**Comment by leamas** [comment]
Now you have pushed to main, which is sort of fine. However, you have *not* pushed to build, so nothing is updated at opencpn-manuals.github.io/plugins. Look into WORKFLOWS again.

>weatherfax needs gitignore docs!!!

So, add it. It's your fork which is used.

> weather_routing/ links

Same, fix them, your repo is the one used

> autopilot_route links

Same

> unresolved antora refs

Only in your plugins, so just fix it:
```
docs/weather_routing/0.1/index.html:<p><a href="#opencpn-plugins:ocpn_draw::index.adoc" class="page unresolved">ODraw_pi</a> Create boundaries for routing avoidance: dangerous areas, sea, land, storm or hurricane.</p>
docs/weather_routing/0.1/index.html:<p><a href="#help_information.adoc" class="page unresolved">Help &gt; Information</a></p>
docs/weather_routing/0.1/index.html:<p><a href="#help_information.adoc" class="page unresolved">Help &gt; Information Menu</a> (Configuration) Help Menus and Definitions</p>
docs/weather_routing/0.1/index.html:<p><a href="#help_information.adoc" class="page unresolved">Help &gt; Information Menu</a> (Configuration) Access this page from the <strong>Help &gt; Information</strong> Menu. Review while stepping through the plugin menus, looking particularly at <strong>Edit Boat.xml</strong> and <strong>Edit Polar File (.csv, .txt, .pol)</strong> Try to understand the menu system. Boat.xml simply contains a list of boat polar files to use in the routing. The polar files can be edited, saved and saved as.</p>
docs/autopilot_route/0.1/index.html:<p>Pypilot Autopilot is available as a managed plugin (PIM), which is the easiest way to install the plugin. The OpenCPN Manual has general information in <a href="#openpcn-plugins:misc:plugin-install.adoc" class="page unresolved">Plugin Download, Install and Enable</a> for installing this plugin. This is the preferred way.</p>
docs/autopilot_route/0.1/index.html:<p>Manual: <a href="#openpcn-plugins:misc:rpi-setups.adoc" class="page unresolved">RPI Pypilot Opencpn</a> Go down to the bottom "Pypilot Autopilot</p>
docs/opencpn-plugins/0.1/authoring/useful.html:<pre>$ grep -r "page unresolved" docs</pre>

```
The last one in useful.html is a false positive.

**Comment by leamas** [comment]
> Tried again and it worked. Did not have any change really. I did try to find something wrong in admiralty and generated antora site.yml successfully but there were no commits needed.

What you did was a rebase. When doing that, you picked up the latest changes in the main branch which fixed the problem.

Rick: VERY interesting. I better get this right.

**Comment by Rasbats** [comment]
@rgleason : Need to rename ` weather_routing_pi/manual/modules/ROOT/pages/help_Information.adoc`  to read:
 `weather_routing_pi/manual/modules/ROOT/pages/help_information.adoc` 
Case sensitive!

**Comment by Rasbats** [comment]
@rgleason : Also for weather routing:-
* xref:opencpn-plugins:ocpn_draw::index.adoc[ODraw_pi]
Should be:
* xref:ocpn_draw::index.adoc[ODraw_pi]

Rick wrote: Thanks Mike, second time around, my eyesight or it was getting late.

**Comment by leamas** [comment]
@rgleason : Please don't edit other's posts. This is messy anyway, and adding yet another layer like this is IMHO a pain.

**Comment by rgleason** [comment]
Hopefully fixed

- unresolved antora refs
- autopilot_route links
- weather_routing/ links

Have updated all site.yml and antora.yml  titles in opencpn-manuals/<plugins>

**Comment by rgleason** [comment]
```
@rgleason : Need to rename weather_routing_pi/manual/modules/ROOT/pages/help_Information.adoc to read:
weather_routing_pi/manual/modules/ROOT/pages/help_information.adoc
Case sensitive!
```

What I had to do, was from online, remove my remote weather_routing_pi /manual/modules/ROOT/pages/help_Information.adoc  and create a new one with the same content and small case i
(Windows does not push these kinds of capitalization changes in filenames.)

**Comment by rgleason** [comment]
Regarding this error
xref:opencpn-plugins:ocpn_draw::index.adoc[ODraw_pi]

decided to change  all the site.yml  to conform,  
JG merged the pr, 
then changed of that link in weather routing and watchdog.
then changed the opencpn-manuals nav.adoc and other accordingly.  
So that is done.

**Comment by rgleason** [comment]
Have not noted the good links yet.
