### ISSUE TITLE
Autopilot_Route   xref problem

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#55]
I am having lots of trouble figuring out what exactly is wrong with this link

xref:opencpn-plugins:misc:rpi-setups.adoc

also tried   xref::opencpn-plugins:misc:rpi-setups.adoc
For an earlier version that also fails see https://opencpn-manuals.github.io/plugins/autopilot_route/0.1/index.html
at the bottom of the plugin 

Any ideas?

**Comment by rgleason** [comment]
BTW this is almost the same as  Terminology xref used in Weather_routing

xref:opencpn-plugins:misc:terminology.adoc[Terminology Reference] used in this Manual.

My paths to it are exactly the same

```
C:\Users\Rick\Documents\GitHub\OM-plugins\manual\master-plugins\modules\misc\pages\terminology.adoc  
C:\Users\Rick\Documents\GitHub\OM-plugins\manual\master-plugins\modules\misc\pages\rpi-setups.adoc

```
So why isn't that link working?

Now I notice that  miscl.adoc has 

` xref:opencpn-plugins:misc:rpi-setups.adoc[RPI Setups]`

so it should work!

**Comment by Rasbats** [comment]
You have xref::opencpn-plugins. But the ref is inline with other stuff so you need:
xref:opencpn-plugins (Single colon)
On a separate line it would have been ok.

**Comment by rgleason** [comment]
I tried that first. Did not work either

**Comment by Rasbats** [comment]
Even a local build is using site.yml which is pulling the index.adoc from your repo. If you edit the repo again (using :) I will update sources.state and try again.

**Comment by rgleason** [comment]
Ok, thanks. I see your point. Perhaps that wasnt completed. Just got up. Will do in 1/2 hr.

**Comment by rgleason** [comment]
Mike, I made the change to the last xref.  Thanks.

**Comment by rgleason** [comment]
Seems to be working now great thnks
