### ISSUE TITLE
 update ci/w3c-linkcheck.sh to to exclude domains involved

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#58]
> These links work, but are flagged by linkchecker

> http://www.ephemeris.com/ephemeris.php <---Exists not a problem
> http://www.clearskyinstitute.com/ <--- Exists not a problem
> https://forum.openmarine.net/showthread.php?tid=868 <https://forum.openmarine.net/showthread.php?tid=868>
> https://forum.openmarine.net/forumdisplay.php?fid=17 <https://forum.openmarine.net/forumdisplay.php?fid=17>

Alec  - Just update ci/w3c-linkcheck.sh to exclude the domains involved.

**Comment by leamas** [comment]
Yes, like I said: modify  ci/w3c-linkcheck.sh to accept also these domains. If you look into the file you should understand how to add some lines to accomplish this.

**Comment by rgleason** [comment]
Will do..  Have been having lots of other troubles with this new "system"

**Comment by rgleason** [comment]
https://github.com/opencpn-manuals/plugins/commit/a1cba062467ffe53b836ac51afe79b703eb119d3
