### ISSUE TITLE
sources.state  file trying to add windvane back in 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#59]
Using the most current sha from JG gitthub.com/jongough/windvane_pii   

1. first save the file.
2.  ./source-state.sh save    
3. Afterwards we had in the last line

windvane_pi https://github.com/jongough/windvane_pi.git 44e8b986e423d7033d83b40a9ff7b0f40f205768

1.  ./source-state.sh update

last line disappears. again, every time.

site.yml has windvane_pi listed properly.

1.  ./source-state.sh restore  works with no complaints at all, but no windvane_pi
 
Example
 
```
Restoring into vdr_pi
From https://github.com/rgleason/vdr_pi
 * branch            5503ac81136c12496985bbea24ca1fc45d08309c -> FETCH_HEAD
Restoring into vfkaps_pi
From https://github.com/rasbats/vfkaps_pi
 * branch            00bc1485a8a02cd696e9f770cafd0a217aa8588c -> FETCH_HEAD
Restoring into watchdog_pi
From https://github.com/rgleason/watchdog_pi
 * branch            16374cdf9ffcb3d8db37b2244cee012aecfb06c9 -> FETCH_HEAD
Restoring into weather_routing_pi
From https://github.com/rgleason/weather_routing_pi
 * branch            3ffe63a70a12577c6b477e961ebf90b0f855da02 -> FETCH_HEAD
Restoring into weatherfax_pi
From https://github.com/rgleason/weatherfax_pi
 * branch            86ef95e9ef2bf52675b1c0f091b984500315d3dc -> FETCH_HEAD
```

**Comment by rgleason** [comment]
next try antora site.yml

Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ antora site.yml
error: Local content source does not exist: C:\Users\Rick\documents\github\OM-plugins\sources\windvane_pi (url: sources/windvane_pi)
Add the --stacktrace option to see the cause.

and we know why.

**Comment by rgleason** [comment]
Maybe this will help fix this. here is my sources.state  with .txt added, but no windvane_pi at the end.
[sources.state.txt](https://github.com/opencpn-manuals/plugins/files/7190743/sources.state.txt)
e

**Comment by rgleason** [comment]
Check sources output.txt   

[check-sources-output.txt](https://github.com/opencpn-manuals/plugins/files/7190746/check-sources-output.txt)

I am not going to push this now.  Will stop.

**Comment by Rasbats** [comment]
GPS-Odometer had the wrong URL in sources.state. Now fixed.

**Comment by rgleason** [comment]
How did you know that?
Check-source and source-state update did not show anything and windvane was failing.

What a waste of time this was

**Comment by Rasbats** [comment]
When I had to make local sources (restore - no sources) everything stopped downloading after gecomapi. The plugin after this is GPS-Odometer!

**Comment by rgleason** [comment]
The script is different now. I would try ./sources-state.sh update or restore and it would clean out sources.state automatically and add some name on the comnit. I think if you have to do two restore in a row because first is screwed up, it cleanz the slate. Also when I tried manually putting in windevane path and sha, then ./source-state.sh save then when I did ./source.state update then windvane was removed!

**Comment by leamas** [comment]
> GPS-Odometer had the wrong URL in sources.state. Now fixed.

No. It was right since I patched it in b0d44aca  (you have not changed that entry in site.yml after that)

What you miss is that when things moves, for example when I push a commit on opencpn-manuals, you must pick up these changes locally. This is what _git rebase_ does in orderly, safe and much better way than _git pull_

Seems that I will need to write a new note in the git crash course.

**Comment by leamas** [comment]
> The script is different now. 

This statement is not really useful. However, if you say something like "I'm currently at commit deadbee; the script is different here" others have a chance to understand where you are. But without a commit (that is, the value of HEAD), we are all lost

**Comment by leamas** [comment]
sources.state is OK at c8f6d1c.,I run a _./source-state.sh restore_ without problems. **If** there are problems, it could be handled in two ways:

  - If the restore fails for a specific plugin, just remove the corresponding directory under sources/ and re-run _./source-state.sh restore_.
  - If this does not help: Remove all directories under _sources/_ (but keep the .gitkeep file). Then run _./source-state.sh restore_ again. It takes some time, but will otherwise work.

**Comment by rgleason** [comment]
Ok, so we must have Head's SHA.  I hope your git tutorial can give guidelines/ step by step example for
1. Editing standard distributed plugins
2. Editing internal plugins
3. Editing the plugin index structure. IE nav.adoc's  index.adoc's etc.

**Comment by leamas** [comment]
>  hope your git tutorial can give guidelines/ step by step example for
[snip]

probably no.

**Comment by leamas** [comment]
> Editing standard distributed plugins

I think you do this successfully today. That is, edit the sources, commit and pushes to the repo for those plugins that you maintain. This is basically no problem, the problems are related to your attempts to update the opencpn-manuals/plugins repo
