### ISSUE TITLE
Discontinue IACfleet?

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#60]
Perhaps we should retire IACfleet and concentrate on the other plugins.

https://github.com/nohal/iacfleet_pi/issues/22

**Comment by rgleason** [comment]
I have been unable to enter these links because of other issues which have prevented me from completing a push.

**Comment by leamas** [comment]
Anyway, this plugin is basically now in the hands of Pavel. He is the one who should reply to nohal/iacfleet_pi#22, and he is the manual maintainer. 

So, we just leave this as it is.  It's Pavel's desk, and he knows, it. What you perhaps could do is to file yet another bug about the need to actually write the manual page (and file it against https://github.com/nohal/iacfleet_pi)

**Comment by leamas** [comment]
Otherwise, I think we should close this. The question about discontinuing iacfleet is not about the manual.

**Comment by rgleason** [comment]
It should be discontinued in the manual. I cobbled the manual page years ago and it has not been maintained. This is about the Manual. Pavel can keep his repository and I really think he should, because hopefully its use will reappear just like it would be useful if Loran reappeared.  

We just don't need IACfleet in the manual.  There is no active data for it, so it is totally useless. Remove it I say.  This is about the manual and misleading Users.     So this issue should not be closed.

**Comment by leamas** [comment]
Well, you have full commit rights. So, just remove it from site.yml, sources.state and the navigation links.

**Comment by rgleason** [comment]
I was just looking for a little affirmation, but since I have it from David Burch, who I consider an authority, I will remove it.  Thanks for your help.

**Comment by rgleason** [comment]
https://github.com/opencpn-manuals/plugins/commit/5bfbe896c76686921da289e75efd7aa2696795bf
