### ISSUE TITLE
Edit this Page  - Internal Plugins

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#61]
I have made changes to Grib_pi and  Dashboard_pi  and commited those changes to the "build" branch.
Will those changes please be accepted into the "main" branch?

I hope they will not be "lost"

**Comment by Rasbats** [comment]
Could you save those changes somewhere/Checkout main/Copy the changes to the files in main/Commit to main?
Otherwise any use of `git push -f origin main:build` will result in losing them.

**Comment by rgleason** [comment]
Ok I was just making more changes to the Grib_pi links and all the prior changes are not there!

This is not going to work for me. It is a complete waste of time

https://github.com/opencpn-manuals/plugins/blob/build/manual/master-plugins/modules/grib_weather/pages/grib_weather.adoc

The button says "Edit this page!" 
How can anyone edit these documents reliably wiithout jumping through hoops?

**Comment by rgleason** [comment]
This is turning into a big mess. I need to know the steps to take.  I've lost a morrning's work.  
No more.  We need step by step for different actions that need to be taken to edit:

1. Typical Plugins that are distributed to repositories - 
2. Internal Plugins
3. Plugin  Nav.adoc, Index.adoc and misc documents.adoc

They are all different and we need to know how we can avoid stomping all over each others work.

**Comment by leamas** [comment]
You can (and probably should) use the same workflow for 2) and 3). This is the workflow described in WORKFLOWS.md, look for Basic, Minor Change.  It assumes that you don't use  Edit This Link  but rather make changes directly in the sources.

I assume that you already are handling 1) fine. That is, edit sources, commit and push to github for plugins that you maintain.

**Comment by rgleason** [comment]
Could this be put in Workflow, it might help all of us.

1. Typical Plugins that are distributed to repositories
2.  Internal Plugins  use Workflow - Basic Minor Change  (no Edit this page) make changes directly in the sources.
3. Plugin Nav.adoc, Index.adoc and misc documents.adoc  use Workflow -Basic Minor Change (no Edit this page)

Number 1  above. For PI you maintain,  Edit sources, commit and push to github.
Number 2 & 3 above. Use Workflow  "Basic Minor Change"  directly in the sources  (no Edit this page) .

**Comment by leamas** [comment]
Well, you can change it. Do it!

**Comment by rgleason** [comment]
Ok Thanks

**Comment by rgleason** [comment]
https://github.com/opencpn-manuals/plugins/commit/0bc313f328362f536012e96775d6d3d4f1924af9
