### ISSUE TITLE
Edit This Page for main project: wrong branch build

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#65]
From https://github.com/opencpn-manuals/plugins/issues/62#issuecomment-922515836

> Edit this page" for the included plugins from the website page takes you to the build branch because that is where the gh-pages come from.

We need to either fix the link or disable it

**Comment by Rasbats** [comment]
commit 134dd0f27e8bf74a06c20f22e924714fa81db917 disables "Edit this page" for the included plugins and pages drawn from the main manual repo. "Edit this page"  is available for all dev repo plugins.
@leamas @rgleason  Comments please.

**Comment by leamas** [comment]
I'll look into if it's possible to generate a correct url later. If so, I see a value for casual drive-by fixes by users.

However, having this like this for now will get around the buggy url. No url is way better than wrong one. And, it will teach us (you, me and Rick) to use the regular edit-commit-push workflow when maintaining the manual. Which is what **we** should use in any case.

**Comment by leamas** [comment]
Ergo: 134dd0f  is the right thing to do now, but let's leave bug open until I have looked into patching the url.

**Comment by rgleason** [comment]
Thanks that will be better for good habits.

**Comment by leamas** [comment]
When  we are ready to once again relaunch Edit This Page link, below patch which makes the link point to the proper url

```
From 85bdc7b533bdb71bb90b539a6cc28a96796430ee Mon Sep 17 00:00:00 2001
From: Alec Leamas <leamas.alec@nowhere.nt>
Date: Mon, 20 Sep 2021 15:24:14 +0200
Subject: [PATCH] Modify edit_url to correct value

---
 site.yml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/site.yml b/site.yml
index 589884f..becf46d 100644
--- a/site.yml
+++ b/site.yml
@@ -11,7 +11,7 @@ content:
       start_paths:
       - manual/master-plugins
       - manual/beta-plugins
-      edit_url: ~
+      edit_url: https://github.com/opencpn-manuals/plugins/edit/main/{path}
 
     # @@plugin-list-begin    Keep this comment, used by main project
     - url: sources/admiralty_tide_tables_pi
-- 
2.31.1


```

**Comment by leamas** [comment]
@Rasbats  @rgleason: I have re-introduced the Edit This Page for this very repository in 5e234e4. We should not probably not use it ourselves, but it does add value for casual drive-by edits.

Closing
