### ISSUE TITLE
Regarding Forking to opencpn-manuals

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#66]
We cannot use the typical  Antora "Edit this page" button to propose changes to underlying files because those files are not available. 

So when we want to make changes in a manual to the underlying files, when the PI is not managed by us we have a choice, to fork to

- opencpn-manuals
- to our own account

Which Account should be used?  

- Leamas said that if we use  - opencpn-manuals   so the fork lands there, all 3 of us can make changes.
- Rasbats said when I did just that (forked to opencpn-manuals)  to Calculator_pi that he could not merge the changes that it was blocked.

**Comment by rgleason** [comment]
Is the reason Rasbats could not merge the Calculator  commit because I have to then push that change up to remote? 

I don't think that  the fork goes locallly that is not how other forks work.  (forked from rasbats/calculator  to opencpn-manuals) and it should appear at github.com/opencpn-manuals/

But I don't see calculator_pi there now!!  https://github.com/opencpn-manuals 

So where did it go?

**Comment by leamas** [comment]
This is definitely not an issue as such, it's a question better handled in the overall discussions forum in the main repo: https://github.com/opencpn-manuals/main/discussions

**Comment by leamas** [comment]
Handled in https://github.com/opencpn-manuals/main/discussions/18. Closing
