### ISSUE TITLE
Concurrency Question when 3 are working

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#67]
### Working with others:   Is this correct?

RE: https://github.com/opencpn-manuals/main/discussions/14#discussioncomment-1354650
> ..we need to "import" these new commits to our own clones as soon as possible.

1. If I go to my local opencpn-manuals/plugins before starting work  **_Keep the Repro in Sync_**

> Before doing work involving the github repo we do git remote update origin . This assures that other git commands have up to date information about github's state.

` git remote update origin`   before I start any work.

2. Then I should see the state of the commits with

`git log --oneline -6 
`
If the HEAD-->Main is not on top, there are other commits available in the remote.

3. So we need to import those to local

` git rebase origin/main.
`

4. Now we can do some work and git add and make commits to my local opencpn-manuals/plugins

Meanwhile some time has passed and two other people are busy working & making commits.
So just before **_Updating the Remote_**    I need to check with git log again

`git log --oneline -6 
`
If the HEAD --> main is above all commits that are not recently made by you, then you can proceed, otherwise do another

` git rebase origin/main.     to import commits from remote to your local
`

5. After that we should then  immediately  **_Update the Remote_** 

` git push -f origin main:build
`
and

` git push origin main:main
`

Also what problems exactly should we be looking for between these last two git push?

**Comment by leamas** [comment]
This is definitely to abuse the issue tracker for support issues and discussions. I'm closing this,  aim to reply later in https://github.com/opencpn-manuals/main/discussions/14 i. e., the place where this was published

**Comment by rgleason** [comment]
I did not want to mess up your discussion thread.
