### ISSUE TITLE
Yet another merge commit: non-linear history

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#68]
We have yet another merge commit in main (6070624). 

I think we have a common understanding that these should be avoided. If not else, because of the horrors involved in handling merged histories and not least undoing a merge commit.

@rasbats: How can we avoid these merges?

**Comment by Rasbats** [comment]
The work itself is not mine. I updated my clone and in doing so pulled this in from the repo. Used the Github Desktop. 
commit c044b7552076dd8fe18c082801c955518a0f5ff0 was the initial commit. 
I think the problem comes when a.n.other has made a commit of stuff that is not in my clone. 
Sorry ... must get used to using `rebase` from the CLI. But Github Desktop is so easy! Histories at a glance etc etc etc

**Comment by Rasbats** [comment]
Would this help me?
[https://github.com/desktop/desktop/issues/3422](https://github.com/desktop/desktop/issues/3422)
and **pull.rebase=true** set in the Git config

**Comment by leamas** [comment]
> nd in doing so pulled this in from the repo. 

You must not pull, that is the bottom line. "git pull" is an implicit merge. The exception is when it is possible to do a fast-forward since this does not create a merge commit. But to be sure it's  a fast-forward, you must rebase first...

> Would this help me [...]

I don't fully understand what's going on here. Have they, or have they not implemented the requested functionality? That said, this issue shows that the need for a rebase rather than pull/merge is not unique...

A helpful thing would probably be to mark the main branch as [ff only](https://code-maven.com/enforce-fast-forward-as-merge-strategy). Note that we cannot apply this globally because of how we handle the _build_ branch, it must be for the _main_ branch only. EDIT: No, this will not work. EDIT2: more thinking... actually, it should work (!)

At a glance, it seems that the gui has [support for rebasing](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch#rebasing-your-project-branch-onto-another-branch). If you do this instead of git pull using the sync button it should work. OTOH, this seems rather complicated compared to the command line oneliner.

Another option might be the git integration which seems to be available in VS and VS Code. No idea what they are capable of. I know, however, that only thing which supports all git functionality is the command line client :)

**Comment by leamas** [comment]
I'm BTW also looking at a pre-push commit hook which refuses to push merge commits. I have a sketch, but it needs testing...

**Comment by leamas** [comment]
@rasbats: EDIT2^^

**Comment by leamas** [comment]
> I think the problem comes when a.n.other has made a commit of stuff that is not in my clone.

Exactly, I should have replied earlier on this. When this happens the history has forked into to different paths, one on github and one local.  This is a fact which can be dealt with by making a merge commit (Ugh!) or re-creating a new history with the github commits first, and your unpushed commits on top of that. This is what rebase is all about.

**Comment by Rasbats** [comment]
I have tried this:

`$ git config --local pull.rebase true
`
You may want to make a small edit to something in the main manual and I will test a pull.rebase with Desktop.

**Comment by leamas** [comment]
I'm looking into that, stay tuned. That will not work, it will interfere with the build branch. Hang on...

**Comment by leamas** [comment]
A slight variant seems to work: 

    $ git config branch.main.mergeOptions "--ff-only"
    $ git config branch.main.rebase true

I have pushed a silly test commit, it seems possible to make a sane pull. And the first one should block whatever local merges that might be created.

You should probably remove the ` pull.rebase true `entry you have in your .git/config before applying changes above. The easiest is to edit .git/config and remove the line, it's nto hard to find.

**Comment by leamas** [comment]
EDIT: Too fast. Again! stay tuned...

**Comment by leamas** [comment]
false alarm, it looks sane: https://stackoverflow.com/questions/13846300/how-to-make-git-pull-use-rebase-by-default-for-all-my-repositories

**Comment by Rasbats** [comment]
Works for a change I made myself, using Desktop!

**Comment by leamas** [comment]
Since this is about configuring git, it should work with whatever frontend used, GUI or not. This is expected.

Thanks for all your input, you found the right track!

Seems that this is resolved according to https://github.com/opencpn-manuals/plugins/issues/68#issuecomment-922803001, although we  need to git @rgleason  onboard as well. It's less pressing for him since he is using the cli tools, though. Closing

**Comment by rgleason** [comment]
This is very interesting and is related directly with my concurrancy question.
