### ISSUE TITLE
Simplify Navigation

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#72]
There is something funny about the navigation, I get caught in Beta Plugin Land and it is hard to get out.
Also there seems to be a Beta nav.adoc that is the same as the header plugiin adoc.

I would think that conceptually we have all plugins documentation in one barrel and dip in there for the Main Plugins and the Beta Plugns, that would make it easier to move a plugin into Main and might make navigation easier. 

I find there might be some room to simplify the folder and layers a bit, but I hesitate to say how as I know you guys have been working with this a lot.   I am just wondering if some changes could be made to make things easier in the long run.

**Comment by rgleason** [comment]
BTW I'm pretty much finished with editing titles and indexes etc. and will likely just be editing individual plugin manuals for awhile. Also I've got to get all of the TP frontend PI updated, its pretty bad right now.

Thanks for putting up with me, I've learned a lot had have a crib sheet for going forward.

**Comment by leamas** [comment]
> BTW I'm pretty much finished with editing titles and indexes  [snip]

This is off-topic, right?

**Comment by leamas** [comment]
> here is something funny about the navigation, I get caught in Beta Plugin Land and it is hard to get out.

The only thing I see is that when actually looking at a plugin (main or beta), the left navigation pane is replaced with a list of plugins, ordered and complete. This is because the plugin manuals does not include or depend on openpcn-manuals/plugins, which is the way it should be for other reasons.  This is not that bad, since:
  - It's just to use the browser 'Back`button to get back to the navigation pane.
  - This list is great when you are searching for a specific plugin but don't know which heading it is under.

**Comment by rgleason** [comment]
Ok, I think may be there should be a Main Plugin link at the top of the Beta page and visa versa.

You definitely get caught in Beta Land. Try it.

**Comment by rgleason** [comment]
Also I think this structure can be simplified. There are two identical pages basically, which are not necessary. 
It has happened because Beta and Main were separate for a long time and they have now been connected. There is some re-organizing needed.

**Comment by leamas** [comment]
> You definitely get caught in Beta Land. Try it.

Just did. Not caught, "Back" button works fine.

>  There is some re-organizing needed.

Perhaps, but then we need a more concrete proposal. And  a better problem description, I don't see any difference when looking at the beta plugins vs the main ones.

**Comment by Rasbats** [comment]
> Also I think this structure can be simplified. 
@leamas @rgleason : I am going to try rather a large reorganisation, removing partials. If this works this would simplify the installation of new plugins and make the whole structure more transparent.
It works on local build ... standby.

**Comment by Rasbats** [comment]
Mistake ... local build was from before the reorganisation. Trying another build.

**Comment by Rasbats** [comment]
Completely screws up the navigation on the left of the page. Still playing.

**Comment by Rasbats** [comment]
As I see it - partials is a way of producing an index. We need an index and this involves adding the xref for the new plugin to the index (partials files nav-plugins.adoc, nav-beta-plugins.adoc).  If you think of nav as the index this may help. 
partials has to stay!

**Comment by Rasbats** [comment]
Link made on the beta page to return to main plugins: commit c9bbd2e0704d8058c2df3a0af94c267e741755d5

**Comment by leamas** [comment]
> [snip] partials has to stay!

I havn't  really shared your mixed feelings about partials from the beginning. That said, I concur with your conclusion.

**Comment by rgleason** [comment]
I may play with this a little if I can find some time.  I should understand it anyway.

**Comment by rgleason** [comment]
Are these pages supposed to be exact duplicates? 

Main & Beta Plugins + Suppl Hrdwr & Softwr,  Authoring  Links
../manual/master-plugins/modules/ROOT/nav.adoc    <--

Short Main & Beta Plugins
../manual/master-plugins/modules/ROOT/pages/index.adoc <--- Duplicate  Could bee the same as top link
../manual/beta-plugins/modules/ROOT/pages/indexs.adoc    <--- Duplicate  Duplicate  Could bee the same as top link

Main Plugins Listing
.../manual/master-plugins/modules/ROOT/pages/plugins.adoc     <--Duplicate
,../manual/master-plugins/modules/ROOT/partials/nav-plugins.adoc  <--Duplicate

Beta Plugins Listing
../manual/beta-plugins/modules/ROOT/nav.adoc    <--References just xref:index..adoc[Home} and xref:beta-plugins.adoc
../manual/beta-plugins/modules/ROOT/pages/beta-plugins.adoc    <--- Duplicate
../manual/master-plugins/modules/ROOT/partials/nav-beta-plugins.adoc  <---Duplicate

**Comment by rgleason** [comment]
It on my plate

**Comment by Rasbats** [comment]
@rgleason : Bit off-topic but ...
[https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/advanced/advanced.html](https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/advanced/advanced.html)

**Comment by leamas** [comment]
I could do some nit-picking here, hope you don't mind. Before doing that: great text!

Some nit-picks:
  - Take for example this snippet:  the following is executed: antora site.yml. The convention generally used is that commands are typed using a monospace font, like `antora site.yml` here.
  - The $source-state restore way of writing a command actually looks weird to me, havn't seen it anywhere (have you?). Again, using a monospace font is the way to show it's a command. The $ is commonly used when command are given on a separate line, but not in running text
  - "This script has 3 options:" This statement is actually plain wrong. First _options_ refers to things with dashes, like  _-l_  or _--quiet_.  A word without dashes is an argument.  And, there is only one argument, which could have one of three values. If you write for a more skilled reader, she would be happy if you first gave the formal description as given in a manpage `source-state-sh <restore|update|save>` Of course, you still need to explain it. But when for example I read that, I immediately understand that the script has a mandatory argument which is one of  restore, update or save.
  - 'sources.state'  is better typed using italics, like _sources.state_. The general approach is that paths and filenames are using _italics_ while commands are using `monospace`.
  - You seem to avoid using subheadings, instead using a bullet list (plugins.adoc, nav-plugins.adoc, etc.) It works, but unfortunately the bullet list headings does not appear in the navigation tree in the right panel :(

**Comment by rgleason** [comment]
Thanks

Well you've done a lot of work there. Doubt it will ever change, but I think current is a bit contorted due to the way the process went and searching for how to do it, not anyone's fault at all!!! 
1. The sources have the manuals, totally separate and all plugins are together under it.
2. The navigation docs can work as you need, keeping it really simple, referencing the sources.
3. The problem  (Actually it is **_Not a problem_**, see below)  is if the nav structure is simplified and changed all the links to all distributed plugins has to change! That is a big job.  (Maybe good regex changes are possible? I don't know this)
4. So when and if this gets done, we would want to be certain about the structure.
5.  I don't have time to devote really, but maybe move beta-plugins into the main plugins somewhere appropriate.
6.  Where are the links to this https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/advanced/advanced.html?  Never saw it.

└─── plugins   **<----  Rename and abandon the beta-plugin navigation branch**
│       │   antora.yml
│       │
│       └───modules
│           ├───advanced    <---Has content in it
│           ├───authoring   <---Has content in it
│           ├───chart_downloader_tab  <---Has content
│           ├───dashboard    <---Has content
│           ├───grib_weather   <---Has content
│           ├───misc    <---Has content
│           │
│           ├───ROOT    <---Where all navigation for External Plugins
│           │   │   nav.adoc   <--Links to plugins.adoc and beta-plugins.adoc and links Internal,  Authoring, etc.
│           │   │
│           │   ├───pages     <-- The only content in this section is the "managed-pi.png !!!
│           │   │       index.adoc   <-- don't know if this should be plugins-main or not.
│           │   │       plugins-main.adoc  <-- Links to sources  (main plugins)
│           │   │       **plugins-beta.adoc    <---Links to sources (beta plugins) -- Add?**
│           │   │       **plugins-all.adoc    <---Links to sources (beta plugins) -- Add?**
│           │   │ 
│           │   └───partials     **<--- Why is this needed?  I don't think it is needed.**
│           ├───sat2chart   <---Has content 
│           └───wmm   <---Has content


I believe this would work fine, and it is much simpler,  but it is a lot of work restructuring it.

**Comment by rgleason** [comment]
**I am starting to realize that the links in most of the plugins will not be affected at all!!!**
The links within the plugins generally all go to to ones with some real content!!!
   
│ ├───advanced <---Has content in it
│ ├───authoring <---Has content in it
│ ├───chart_downloader_tab <---Has content
│ ├───dashboard <---Has content
│ ├───grib_weather <---Has content
│ ├───misc <---Has content
│ ├───sat2chart <---Has content
│ └───wmm <---Has content

So there would NOT be any rework of links in the plugins  (Isn't this right?)

**Comment by rgleason** [comment]
So you could make a new branch, make these changes, test it and then rebase it (almost said merge (:-)) .

**Comment by Rasbats** [comment]
@rgleason : There are other priorities than rebuilding the structure.

**Comment by Rasbats** [comment]
@leamas :

>using italics while commands are using monospace.

Could you give some examples of asciidoc ?

**Comment by leamas** [comment]
Didn't find one one the spot, although I know for sure I have done plenty of them. Attaching a quick translation of a Markdown thing I have at hand.

[LINUX_DEVICES.adoc.gz](https://github.com/opencpn-manuals/plugins/files/7220052/LINUX_DEVICES.adoc.gz)

EDIT: Here is a single example of an in-line command in monospace: search for stty.

**Comment by leamas** [comment]
@Rasbats : BTW, you could compare your description with the description in the top of the source-state.sh script. The latter is correct, and you have missed some things, notably that it's possible to update or restore a single plugin.

**Comment by rgleason** [comment]
> - @rgleason : There are other priorities than rebuilding the structure.

I don't disagree, but I believe it can and should be done later without much trouble.

**Comment by rgleason** [comment]
This has been done.  It is in the Build Branch.  It is quite simple along the lines shown above with some differences.
Look at the structure please to redraw the diagram.

BUILD Branch:   https://github.com/opencpn-manuals/plugins/commits/build   **"Simplify Navigation"**
https://github.com/opencpn-manuals/plugins/commit/230902a0fa79d856434d05a0b93ba47b069a566b

See this html result
https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html

Please take a look and then I will push to Main.  Tomorrow Morning

**Comment by Rasbats** [comment]
@rgleason : Does this build locally for you if you remove partials?
[https://github.com/opencpn-manuals/plugins/blob/build/manual/plugins/modules/ROOT/pages/index.adoc](https://github.com/opencpn-manuals/plugins/blob/build/manual/plugins/modules/ROOT/pages/index.adoc)
This page shows 'Authoring' has no link. Other pages show no link.
Suggest another look.

**Comment by leamas** [comment]
> Does this build locally for you if you remove partials?

Partials is the  underpinnings for the left pane navigation tree. Why is it so important to get rid of it?

>  This page shows 'Authoring' has no link. Other pages show no link.

That's just github rendering asciidoc files, and github does not understand the Antora extended link syntax. OTOH, the real stuff at 
https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html is linked correctly, so this is a red herring

That said I don't actually see any difference in the user navigation, just a cleaned up directory structure. Which is good, but am I missing something?

**Comment by leamas** [comment]
The radical approach would be to remove **all** links  in https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html. That would leave us with descriptions of what's available in the different sections and the left pane navigation tree. Simple and clean from a user perspective.

**Comment by Rasbats** [comment]
>Partials is the underpinnings for the left pane navigation tree. Why is it so important to get rid of it?

Rick was concerned about the work needed to add a new manual and the number of places to edit. I thought this was the impetus for his simplification. Why change it if you still need partials?

**Comment by leamas** [comment]
Well, I see the value of a simpler directory structure now when it's done. Don't you?

**Comment by leamas** [comment]
If we really want to simplify maintenance: https://github.com/opencpn-manuals/plugins/issues/72#issuecomment-927069357

**Comment by rgleason** [comment]
Well it all works for me locally, no problem. I found that I need partials because we have 3 lists that are drawn into the nav bar. Nav-all, nav-main and nav-beta.

May I push this to main branch, then you can work on it more?

Ps i like the navigation as is, just did not like the structure.

**Comment by leamas** [comment]
You don't need permission from anyone, just do it. If someone is upset, he'll have to revert which isn't a big deal.

That said, to me this looks good.

**Comment by rgleason** [comment]
Thanks.  Will first try to do your requested changes to the wiki, then this.

**Comment by rgleason** [comment]
Mike,  I just did another  antora site.yml  locally and your menus are working very nicely including the Authoring and General and Supplementary Information.  I think you will find this much easier to understand and maintain. We basically have to update 

**..\manual\plugins\modules\ROOT**

- nav.adoc     <--- The full left hand Navigation bar
- "partials" -  nav-all.adoc, nav-main.adoc and nav-beta.adoc    <-- Lists imported into the left hand navigation bar
- "page:     - index.adoc, index-main.adoc, index-beta.adoc   <-- Used for Center page

**..\manual\plugins\modules\authoring\pages**

- authoring.adoc    <-- Used for  Center page too


There may be a clever way to use "_partials_" pages in the _index-main.adoc_ and the _index-beta.adoc_
Also to turn the _authoring.adoc_ into a  _partials:nav-authoring.adoc_ and use that in _nav.adoc_ and _authoring.adoc_.

Then we would only have to edit 5 instead of 7 pages.

-   nav.adoc
-   partials:nav-all.adoc
-   partials:nav-main.adoc
-   partials:nav-beta.adoc
-   partials:nav-authoring.adoc

in one place.  But that is for an other time. Perhaps we should just use this for awhile

I hope that helps.

So I am going to rebase and push to main now.

**Comment by rgleason** [comment]
Change main site.yml page to 
site:
  title: OpenCPN
  url: https://opencpn-manuals.github.io/plugins
  start_page:  opencpn-plugins::index.adoc   <--Just this.

**Outline**

│ │ plugins 
│ │ 
│ └── antora.yml   " nav:   - modules/ROOT/nav.adoc"
│ │ 
│ └──modules
│ ├─── advanced <---Has content in it
│ ├─── authoring <---Has content in it also is used for index.adoc
│ ├─── chart_downloader_tab <---Has content
│ ├─── dashboard <---Has content
│ ├─── grib_weather <---Has content
│ ├─── misc <---Has content
│ ├───sat2chart <---Has content
│ └───wmm <---Has content
│ │
│ ├─── ROOT <---Where all navigation for Plugins is done
│ │ ├─────  nav.adoc <--Uses partials files  nav-main.adoc, nav-beta.adoc, nav-all.adoc.  Lefthand Nav bar
│ │ ├─────  antora.yml   
│ │ ├─────  pages <-- These file are displayed in the center page area
│ │ ├────────  index.adoc         <--   Has main links to  Gen. Info,  Main & Beta Plugins, Authoring
│ │ ├────────  index-main.adoc <-- Has the links to sources (main plugins)  (could use partials)
│ │ ├────────  index-beta.adoc <---Has the links to sources (beta plugins) (could use partials)
│ │ ├─────  partials   Lists used in other files like nav.adoc
│ │ ├────────  nav-main.adoc <-- Links to sources (main plugins)
│ │ ├────────  nav-beta.adoc <---Links to sources (beta plugins)
│ │ ├────────  nav-all.adoc <---Links to sources (beta plugins)

**Comment by rgleason** [comment]
```

Rick@Dart MINGW64 ~/documents/github/OM-plugins (nav)
$ git fetch

Rick@Dart MINGW64 ~/documents/github/OM-plugins (nav)
$ git rebase origin/main
Current branch nav is up to date.

Rick@Dart MINGW64 ~/documents/github/OM-plugins (nav)
$ git log --oneline -10
8ef7584 (HEAD -> nav) Simplify Navigation -sm chngs
d2d7c63 (origin/build) [full-linkcheck] empty commit
230902a Simplify Navigation
12e9c3b (origin/main, origin/HEAD, main) [full-linkcheck] empty commit
d5614ec [full-linkcheck] empty commit
84aac89 sml chgs to nav index
5769c7d Update advanced.adoc
80105f3 advanced.adoc
d09063b misc/plugin-install: Update info on supported platforms.
ea53f68 advanced
```

Then push 
`
git push origin nav:main`
$ git push origin nav:main

**Comment by rgleason** [comment]
It appears that these worked and are now in main. Closing

```
8ef7584 (HEAD -> nav) Simplify Navigation -sm chngs
d2d7c63 (origin/build) [full-linkcheck] empty commit
230902a Simplify Navigation
```

**Comment by Rasbats** [comment]
Locally this looks good. Now ... have you pushed to build? Has this been updated for your work in main:
[https://opencpn-manuals.github.io/plugins/](https://opencpn-manuals.github.io/plugins/)

**Comment by rgleason** [comment]
Thanks I am in my  nav branch locally right now, so

```
git checkout main
git pull
   lots of changes

Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git log --oneline -10
8ef7584 (HEAD -> main, origin/main, origin/HEAD, nav) Simplify Navigation -sm chngs
d2d7c63 (origin/build) [full-linkcheck] empty commit
230902a Simplify Navigation
12e9c3b [full-linkcheck] empty commit
d5614ec [full-linkcheck] empty commit
84aac89 sml chgs to nav index
5769c7d Update advanced.adoc
80105f3 advanced.adoc
d09063b misc/plugin-install: Update info on supported platforms.
ea53f68 advanced
```
and now  HEAD seems to be the same as my nav branch, so I am current

Thanks.

**Comment by rgleason** [comment]
That's good that locally it looks good.
I am trying to figure out why your nice expandable  Nav.adoc isn't used all the time,  
when  
the Center page is showing index-main.adoc   (LATER- This is OK, not an issue, shows nav.adoc)
and  index-beta.adoc?    (LATER - This is OK, not an issue shows nav.adoc)
and when you are viewing a plugin   (LATER - this is where the problem is, nav.adoc is not being used!!!)

Note: When you are viewing an internal plugin the nice expandible Nav.adoc is used!!!
I think it should be that way for all the external plugins too.  Do you agree?

See https://github.com/opencpn-manuals/plugins/issues/78

**Comment by rgleason** [comment]
Actually, I totally agree with Alec here, but we need to get the Left Nav Bar working the same for everything (whoops I've been saying the right nav bar!   It is the Left nav bar!!1 )

**Comment by leamas** [comment]
That wxWidgets link is, well, off-topic.

>  we need to get the Left Nav Bar working the same for everything 

Won't happen. This would require that all plugins included the partials from opencpn-manuals/plugins, and this is exactly the kind of dependency we want to avoid. That is,  as soon as we added or removed a plugin we would need to file PRs against all plugins. We shouldn't do that.

Since the "Back" button works just fine, let's drop this idea that it should look the same in all situations.

@rgleason : I have 15 (!) unread messages from you since yesterday. No time to handle them, will just drop.

**Comment by rgleason** [comment]
Alec wrote:
Won't happen. This would require that all plugins included the partials from opencpn-manuals/plugins, and this is exactly the kind of dependency we want to avoid. That is, as soon as we added or removed a plugin we would need to file PRs against all plugins. We shouldn't do that.

It wont require recomplie of all pi if the site.yml  nav: is simply referring to the partials will it?

There would be no need for a pr to the plugins each time. It is a one time pr to each pi once we have it right.

**Comment by rgleason** [comment]
Fine. Most of those were from your requests for help with the wiki. 


@rgleason : I have 15 (!) unread messages from you since yesterday. No time to handle them, will just drop.

**Comment by Rasbats** [comment]
@leamas :I was trying to revert to a state previous to where those failed builds were happening. I reverted 230902a I think? This has probably caused the problem. Is it possible to put that commit back into the work again?
Can I just revert my revert?

**Comment by rgleason** [comment]
@leamas 
I have updated sources.state file so it works again and pushed to build, fulll-linkcheck and then to main.
Then git remote update origin
Then git rebase origin/main   (but I have no changes in main right now)
Then git log --oneline -10   (looks good)
Then  git checkout -b nav-again 
I would like to rebase  commit "Simplify Navigation" 230902a which is in my "nav" branch locally, onto "nav-again" branch.
How would I do that?

**Comment by rgleason** [comment]
I just read 
" You should not rebase commits you have already pushed to a remote host. A consequence may be an inability to git push your local rebased branch to a remote host, leaving your only option to git push --force."

I have already commited and pushed these changes to a remote host

So I need to somehow reapply    "Simplify Navigation" 230902a  from the remote.

I could simply make a new commit with the same changes but doing it manually, using the nav-again" branch.
I would checkout the Simplify Navigation commit, copy the relevant files somewhere and then checkout nav-again and apply those files.

**Comment by leamas** [comment]
No. You should persuade Mike to revert his reverts. You could do that yourself, but somehow you and @rasbats must communicate about this and find some common ground, so better if he does it.

**Comment by leamas** [comment]
... or cherry-pick your previous commits: https://stackoverflow.com/questions/8728093/how-do-i-un-revert-a-reverted-git-commit

**Comment by rgleason** [comment]
Ok I will just wait for the time being, but I believe Mike expects me to do it.

This is in my MAIN branch
```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git log --oneline -20
5e2c8ec (HEAD -> main, origin/main, origin/build, origin/HEAD, nav-again) [full-linkcheck] empty commit
5554a26 sources.state fixed
f74ce0d Remove extra plugins directory from manual.
702141c [full-linkcheck] empty commit
f400056 sources, site.yml: Use RooiDirk's upstream repo (#23).
d87ca47 update authoring
66bcd01 Revert to 80105f3
7382dae [full-linkcheck] empty commit
f2fc7bd Revert to 230902a
2c6aa3d [full-linkcheck] empty commit
60ab868 Revert "chnge antora back with spell error"
ac6887b [full-linkcheck] empty commit
5628d5e chnge antora back with spell error
8ef7584 Simplify Navigation -sm chngs
d2d7c63 [full-linkcheck] empty commit
230902a Simplify Navigation               <---  HERE  there are some small changes to clean up after that.   
12e9c3b [full-linkcheck] empty commit
```
Then in my local NAV2 branch
```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (nav2)
$ git log --oneline -15
f6c97b4 (HEAD -> nav2) remove antora  fix managed icons
3e5d8d0 Remove managed icons
eb55097 remove commented PI
a671f37 [full-linkcheck] empty commit
98dd9d2 sml pi name correction
96ca1cb [full-linkcheck] empty commit
e137910 Simplify Maintenance                   <---- RE APPLY THIS COMMIT  and push to build and check
8ef7584 Simplify Navigation -sm chngs
d2d7c63 [full-linkcheck] empty commit
230902a Simplify Navigation       <---- RE APPLY THIS COMMIT and push to build and check
```

**Comment by rgleason** [comment]
So you want those reverts "reverted"  to clean up the main branch?
How would I do that without a forced push?

**Comment by Rasbats** [comment]
@rgleason : Yes I would like you to make those changes. I will mess it up if I do it.

**Comment by rgleason** [comment]
Ok Mike. I might mess up too, but will go slowly.  Thanks for getting us back to something that works..

Alec, I could do a cherry pick, put my commits at the top, leaving your recent commit and mike's authoring commit, etc then make a commit, test locallly and try pushing it to build.

I will make a summary of what I could do.

**Comment by rgleason** [comment]
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git log --oneline -20
5e2c8ec (HEAD -> main, origin/main, origin/build, origin/HEAD, nav-again) [full-linkcheck] empty commit
5554a26 sources.state fixed                               <--- Pick or Keep
f74ce0d Remove extra plugins directory from manual.  <--- Remove
702141c [full-linkcheck] empty commit             <--  Remove
f400056 sources, site.yml: Use RooiDirk's upstream repo (#23).  <--- Pick or Keep
d87ca47 update authoring                                <--  Pick or Keep
66bcd01 Revert to 80105f3                               <-- Remove
7382dae [full-linkcheck] empty commit           <-- Remove
f2fc7bd Revert to 230902a                               <-- Remove
2c6aa3d [full-linkcheck] empty commit             <-- Remove
60ab868 Revert "chnge antora back with spell error"  <--Remove
ac6887b [full-linkcheck] empty commit            <-- Remove
5628d5e chnge antora back with spell error     <--Remove
8ef7584 Simplify Navigation -sm chngs             <--Remove
d2d7c63 [full-linkcheck] empty commit              <-- Remove
230902a Simplify Navigation               <---  HERE  there are some small changes to clean up after that.   
12e9c3b [full-linkcheck] empty commit

I might have to change something else but will find out.
Is this the right approach?
First after checking everything works locally.   with antora site.yml
Then git push -f  origin main:beta  if completes
do full-linkcheck
Then git push origin main:main
I could do a forced push but you probably would not like that

**Comment by rgleason** [comment]
Actually I was thinking of using interactive git squash
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History  with
p, pick <commit> = use commit
d, drop <commit> = remove commit
etc

$ git rebase -i HEAD~16

**Comment by rgleason** [comment]
After seeing Alex's note above and link, I will cherry pick.

git cherry-pick  230902a    Which is "Simplify Navigation" <--- HERE there are some small changes to clean up after that.

It looks like this after a cleanup commit.
It builds antora site.yml and I've checked all areas including authoring and they work.
That worked so cleanly, I would next like to find the SHA for my "Simplify Maintenance" and use cherry-pick again.

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git log --oneline -20
9fa4f79 (HEAD -> main) two small changes rm unnecessary
61ec910 Simplify Navigation
5e2c8ec (origin/main, origin/build, origin/HEAD) [full-linkcheck] empty commit
5554a26 sources.state fixed
f74ce0d Remove extra plugins directory from manual.
702141c [full-linkcheck] empty commit
f400056 sources, site.yml: Use RooiDirk's upstream repo (#23).
d87ca47 update authoring
66bcd01 Revert to 80105f3
7382dae [full-linkcheck] empty commit
f2fc7bd Revert to 230902a
2c6aa3d [full-linkcheck] empty commit
60ab868 Revert "chnge antora back with spell error"
ac6887b [full-linkcheck] empty commit
5628d5e chnge antora back with spell error
8ef7584 Simplify Navigation -sm chngs
d2d7c63 [full-linkcheck] empty commit
230902a Simplify Navigation
```

**Comment by rgleason** [comment]
The "Simplify Maintenance" was overwritten for some reason and does not appear to be in Main branch any longer.
Perhaps it was not accepted becuase by then nmeaconverter_pi had been merged and sources had changed making  the "windvane" Fatal Error which signals that sources are not in sync.

I do have a commit for "Simplify Maintenance in my "nav2" branch.  I am going to have to read up on how I cherry-pick that commit from another branch.

**Comment by rgleason** [comment]
So we need to cherry-pick  
e137910   Simplify Maintenance   from "nav2" branch onto "main" branch 

It looks like I just need the SHA and 
git checkout main
git cherry-pick e137910 


```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (nav2)
$ git log --oneline -20
f6c97b4 (HEAD -> nav2) remove antora  fix managed icons
3e5d8d0 Remove managed icons
eb55097 remove commented PI
a671f37 [full-linkcheck] empty commit
98dd9d2 sml pi name correction
96ca1cb [full-linkcheck] empty commit
e137910 Simplify Maintenance   <------ Need to Cherry Pick this 
8ef7584 Simplify Navigation -sm chngs
d2d7c63 [full-linkcheck] empty commit
230902a Simplify Navigation
```

**Comment by rgleason** [comment]
So now it looks like this

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git log --oneline -10
1d1bfcd (HEAD -> main) small pi name changes
0556fce Simplify Maintenance resolve conflicts
9fa4f79 two small changes rm unnecessary
61ec910 Simplify Navigation
5e2c8ec (origin/main, origin/build, origin/HEAD) [full-linkcheck] empty commit
5554a26 sources.state fixed
f74ce0d Remove extra plugins directory from manual.
702141c [full-linkcheck] empty commit
f400056 sources, site.yml: Use RooiDirk's upstream repo (#23).
d87ca47 update authoring
```

and it works locally, but the build fails here

```
From https://github.com/opencpn-manuals/plugins
 * branch            1d1bfcdbca027d600144623b019c81c0aa0dc19b -> FETCH_HEAD
+ msg='[CI] Updating gh-pages branch from 1d1bfcdb'
+ [[ 1d1bfcd small pi name changes == *full?linkcheck* ]]
+ git commit -q -m '[CI] Updating gh-pages branch from 1d1bfcdb'
+ git push -f origin pages:gh-pages
To https://github.com/opencpn-manuals/plugins
 ! [remote rejected] pages -> gh-pages (cannot lock ref 'refs/heads/gh-pages': is at 577ba9be48e74c8e202a18756c273e4de11a7ee0 but expected e51a9103c9fff7d8bdf352bf0356aea10a4b9365)
error: failed to push some refs to 'https://github.com/opencpn-manuals/plugins'
```

I don't know what this problem is.

**Comment by rgleason** [comment]
Full Link check seems to have completed now.
I am going to check sources....  later, I made a commit for new sources-state file and committed then pushed and pushed empty full-linkcheck.

**Comment by rgleason** [comment]
The Full-Linkcheck completed twice so I git push origin main:main.

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git log --oneline -8
0e0456a (HEAD -> main, origin/main, origin/build, origin/HEAD) [full-linkcheck] empty commit
dfa6a46 [full-linkcheck] empty commit
1d1bfcd small pi name changes
0556fce Simplify Maintenance resolve conflicts
9fa4f79 two small changes rm unnecessary
61ec910 Simplify Navigation
5e2c8ec [full-linkcheck] empty commit
5554a26 sources.state fixed
```

I believe it is working now. 
I really like git cherry-pick  it is a wonderful tool.
Tomorrow I will make a few changes to the Authoring page after you guys have a chance to look at it.

**Comment by Rasbats** [comment]
@rgleason : Rick ... Hats Off. This looks good. Updated sources.state and pushed to main/build. Generated web pages look good.

**Comment by rgleason** [comment]
That is great. We had success! I updated sources.state and pushed it before the second linkcheck but for some reason it did not show on build or main.  Thanks very much.

May I change the diagram in authoring and add a few notes about maintenance files?

Boy is cherry pick a sweet little tool!

**Comment by rgleason** [comment]
Mike I tried making my changes through the Edit this page   (I probably shouldnt have) but I hope they work.

https://github.com/opencpn-manuals/plugins/blob/main/manual/plugins/modules/advanced/pages/advanced.adoc
