### ISSUE TITLE
Navigation: Hard to find plugin by name

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#73]
In many cases, a user knows the name of a plugin  and wants to find that manual. However, this is pretty complicated today, one needs to first know if it is a "beta" plugin or included in the "main" section. In the latter case, one also needs to know which heading (navigation, weather, etc.) it lives under.

The natural remedy is probably to add a new navigation item "All plugins A-Z" which gives an alternative path to a plugin with a known name.

I have a patch at hand, but the build collided with Mike's so I stopped it. 

@Rasbats : thoughts?

**Comment by Rasbats** [comment]
> "All plugins A-Z" 

Would be useful. Have held back but ... have you looked at adding a search engine to the ux?

**Comment by leamas** [comment]
> have you looked at adding a search engine to the ux?

I have of course had the same thought, so yes. The simple shortcut is to link to google using "site:". However, they are using a for me unknown template engine in the UI, so it will still take some time.

Suggestion: Can you file a bug so we can track it, but let's for now focus on getting some kind of "release 1" in place reasonably synced with the upcoming 5.6.0 beta which is Real Soon (TM).

**Comment by leamas** [comment]
I will start building this patch now, so if you want to check the current HTML, now is the time....

**Comment by leamas** [comment]
Fixed in 5295200. Closing
