### ISSUE TITLE
Dashboard_tactics  in the Manual

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#75]
I would like to get Dashboard Tactics into the final manual.

Last night I had trouble last night making sources work 
See https://github.com/opencpn-manuals/main/discussions/20#discussioncomment-1362579

It looks like the wheels are now churning.  How hard it is to get Dashboard Tactics into the "Main" manual after you have done your work?

I had no idea there were going to be two "Versions"

**Comment by leamas** [comment]
>  How hard it is to get Dashboard Tactics into the "Main" manual after you have done your work

It is nt an issue. If it is included here, it will go into main, no problems.

**Comment by rgleason** [comment]
Thanks. Working on it.
