### ISSUE TITLE
Simplify Maintenance

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#80]
I've pushed some slightly revised  index-main.adoc and index-beta.adoc which use the partials files nav-main.adoc and nav-beta.adoc. 

which build and work fine locally.  Unfortunately when 
$ git push -f origin nav2:build

does not complete due to some issue with windvane. 
I have not touched or updated sources 

https://github.com/opencpn-manuals/plugins/runs/3714633826

What should I do next?

**Comment by rgleason** [comment]
These changes make it necessary to only edit 5 files when there are changes or additions to the documents.

1. Main Plugins -    ROOT:partials:nav-main.adoc
2. Beta Plugins -    ROOT:partials:nav-beta.adoc
3. All plugins (sorted) -  ROOT:partials:nav-all.adoc
4. Authoring -   authoring/pages/author.adoc
5. General and Supplementary Information -  misc/pages/misc.adoc 

I would like to get them pushed to main  

https://github.com/opencpn-manuals/plugins/commit/a671f37480bcde7691f5d88b0cca381b196a56f0

**Comment by rgleason** [comment]
Here is a comparison of  commits on main and nav2

```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git log --oneline -10
8ef7584 (HEAD -> main, origin/main, origin/HEAD, nav) Simplify Navigation -sm chngs   <------Here completes
d2d7c63 [full-linkcheck] empty commit
230902a Simplify Navigation
12e9c3b [full-linkcheck] empty commit
d5614ec [full-linkcheck] empty commit
84aac89 sml chgs to nav index
5769c7d Update advanced.adoc
80105f3 advanced.adoc
d09063b misc/plugin-install: Update info on supported platforms.
ea53f68 advanced

Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git checkout nav2
Switched to branch 'nav2'

Rick@Dart MINGW64 ~/documents/github/OM-plugins (nav2)
$ git log --oneline -10
a671f37 (HEAD -> nav2, origin/build) [full-linkcheck] empty commit
98dd9d2 sml pi name correction
96ca1cb [full-linkcheck] empty commit
e137910 Simplify Maintenance        <--- Here it FAILS
8ef7584 (origin/main, origin/HEAD, nav, main) Simplify Navigation -sm chngs  <--- Here it completes
d2d7c63 [full-linkcheck] empty commit
230902a Simplify Navigation
12e9c3b [full-linkcheck] empty commit
d5614ec [full-linkcheck] empty commit
84aac89 sml chgs to nav index

```

There is no apparent reason that nav2 should not build.

**Comment by rgleason** [comment]
I see nothing out of place here that I know of

https://github.com/opencpn-manuals/plugins/commit/e137910650bf01c94cd14ff5b985921f68df318a

**Comment by rgleason** [comment]
It does not appear to be the managed-plugin icons or the commented out  lines.

**Comment by rgleason** [comment]
I've tried and tested removing an antora.yml file that is apparently not needed, run antora site.yml locally and it works.  Have also removed all the comment outs made in nav doc lists and have put the managed icons back.

It still fails at

```
 From https://github.com/rgleason/weather_routing_pi
 * branch            89ce242dd81f505b1b5277ea54eb6b0deaf608b7 -> FETCH_HEAD
Restoring into windvane_pi
Cloning into 'windvane_pi'...
From https://github.com/jongough/windvane_pi
 * branch            44e8b986e423d7033d83b40a9ff7b0f40f205768 -> FETCH_HEAD
+ antora site.yml
error: playbook file not found at /home/runner/work/plugins/plugins/site.yml (path: site.yml, cwd: /home/runner/work/plugins/plugins)
Add the --stacktrace option to see the cause.
Error: Process completed with exit code 1.
```

I've had that same thing before.

**Comment by rgleason** [comment]
I have spent the evening trying to figure out why this would not build and fails once again on windvane.
It took awhile, but this has plagued me since the beginning.  It appears that  ncdf is failing, Something has changed with the plugins, unbeknownst to me. 

```
From https://github.com/rgleason/LogbookKonni_pi
 * branch            eca726671517e823048caba4981d821d19bd04b3 -> FETCH_HEAD
Restoring into ncdf_pi
Cloning into 'ncdf_pi'...
From https://github.com/Rasbats/ncdf_pi
 * branch            82b13e4c735d75cde41c2c2c7781c72509e83d46 -> FETCH_HEAD
Restoring into NmeaConverter_pi
Cloning into 'NmeaConverter_pi'...
fatal: could not read Username for 'https://github.com': No such device or address
./source-state.sh: line 70: cd: NmeaConverter_pi: No such file or directory
./source-state.sh: line 108: cd: NmeaConverter_pi: No such file or directory
fatal: remote error: upload-pack: not our ref 53da252f42d201334eaf6544ee32b98c750662f5
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
Restoring into objsearch_pi
Cloning into 'objsearch_pi'...


```

Would this be causing windvane to show up as an error too?

What do I have to do to fix this?

Why did it happen?    It built perfectly well before, what changed to cause this to happen?

**Comment by Rasbats** [comment]
No time. The build log is telling me that you don't have an antora.yml file in the plugins directory.
Edit: Probably not as simple as that. site.yml has not been found.

**Comment by rgleason** [comment]
Windvane does have site.yml and antora
I checked.

I think this is actually something related to ncdf.  Has something changed there?  I dont understand that error.

**Comment by Rasbats** [comment]
Nothing has changed apart from your commits.

**Comment by leamas** [comment]
I have pushed a new upstream for NmeaConverter. As usual, remove the offending plugin (here: sources/NmeaConverter_pi) and re-run _restore_. If it doesn't help, remove everything under sources/ (not .gitkeep) and restore it again.

**Comment by Rasbats** [comment]
I have a new manual to add. JavaScript (Tony Voss). Do I make the commit? What happens if we revert commits from Rick?

**Comment by rgleason** [comment]
If ir is ok to revert go abead. I will then git remote update origin. And git rebase origin/main.  Thanks leamas. I still have no clue where to find the real errors that cause windvane to false fail.

**Comment by Rasbats** [comment]
Now trying to revert to Alec's commit for nmeaconverter.

**Comment by Rasbats** [comment]
Wrong Alec's commit was not to the main branch.

**Comment by leamas** [comment]
> I have a new manual to add. JavaScript (Tony Voss). Do I make the commit? What happens if we revert commits from Rick?

These are independent decisions. You could revert Rick's commits or not, and  later push your changes. It's really no problem.

The current state of sources.state is fine, _restore_ works out of the box. I would just push my changes and postpone the decision to revert 5628d5ed  and/or 8ef75849 to later.

**Comment by leamas** [comment]
> Now trying to revert to Alec's commit for nmeaconverter.

Fine if you do it locally, but please don't push that revert. The commit is OK, and builds fine for at least me 

> Wrong Alec's commit was not to the main branch.

Indeed, I was interrupted. Now it's there: f400056a

**Comment by leamas** [comment]
... which means that everyone else needs to rebase.

**Comment by Rasbats** [comment]
We have a total mess, partly caused by me trying to revert. Alec ... can you take us back to a sane commit that will build. My reverted one did not.

**Comment by leamas** [comment]
After rebuilding current main at f400056a8f I see no immediate problem: _restore_ works as it should, as does _antora site.yml_ At a glance, the manual looks sane.

The comments to the revert commits are misleading. A revert commit does not wind-down the history to a given a commit, it just undoes a commit . So, you don't _Revert to deedbee_, you  _Revert deadbee_ .

Revert commits might generate conflicts on a more human level, especially when reverting someone else's commits. One way to minimize such conflicts is to describe why they are done, possibly by linking to an issue where it's discussed.

**Comment by Rasbats** [comment]
But if you try an empty commit and `$ git push -f origin main:build` it will not complete without an error.

**Comment by leamas** [comment]
Indeed, it's looking for site.yml using the wrong path: /home/runner/work/plugins/plugins/site.yml, I assume it should be /home/runner/work/plugins/site.yml. No idea why, there is no change of directory in the script before it happens

**Comment by leamas** [comment]
The build-and-deploy script was last changed August, 14; same for .github/workflows/main.yml. 

Strange...

**Comment by leamas** [comment]
... and it completes successfully  without [full-linkcheck]. And so does your build of 702141c9. What is the difference?

**Comment by Rasbats** [comment]
>These changes make it necessary to only edit 5 files when there are changes or additions to the documents.

@rgleason : I don't see any difference with your structure. Still plugins.adoc and beta-plugins.adoc to edit. 
Please can you update the structure diagram in advanced.adoc.

**Comment by Rasbats** [comment]
And  a couple of files to remove? test.adoc and antora.adoc?

**Comment by Rasbats** [comment]
I give up ... lots of duplicated files.

**Comment by rgleason** [comment]
```

    These changes make it necessary to only edit 5 files when there are changes or additions to the documents.

@rgleason : I don't see any difference with your structure. Still plugins.adoc and beta-plugins.adoc to edit.
Please can you update the structure diagram in advanced.adoc.
```

I believe this is because you do not rebase  and it keeps causing me problems too.  Now all my changes to Simplify Navigation are gone because you pushed your changes up without rebasing I believe.

 I thought you were just going to drop  Simplify Maintenance (on my local nav2 branch)  and not drop  Simplify Navigation  (oon my local nav branch) and I was going to commit Simplify Maintenance again from my local nav2 branch.


Also I can't get sources restored properly for some reason,  so I am going to try force pulling main

**Comment by leamas** [comment]
> But if you try an empty commit and $ git push -f origin main:build it will not complete without an error.

seems that it works now, no idea what happened in between. Most important: pushing  current origin/main f400056a to origin/build completes, as does your test build with a [full-linkcheck] at 702141c9.

**Comment by Rasbats** [comment]
>I thought you were just going to drop Simplify Maintenance (on my local nav2 branch) 

There is no nav2 branch here.

**Comment by leamas** [comment]
Whatever branches you have on your local machine is your business, no-one else is involved in that.

**Comment by rgleason** [comment]
Yes, but why couldn't you have checked out
https://github.com/opencpn-manuals/plugins/commit/230902a0fa79d856434d05a0b93ba47b069a566b   Simplify Navigation and then rebase your changes on that?

I am letting you all know that I have the changes for 
Simplify Navigation  in a local nav branch
Simplify Maintenance in a local nav2 branch

Both of these work fine locally and I have tested them extensively.
Because I have them in branches we don't have to recreate them, but I will have to figure out how to rebase and apply them again.

**Comment by leamas** [comment]
There is no need to apply them again. If they have been applied at one point, they are in the history.

What you need is find consensus with Rasbats about these changes: should they be included or not.

**Comment by rgleason** [comment]
As I have written extensively and stated before the structure as it is now is difficult to understand and convoluted because of the way it was built up gradually.  The new structure is much cleaner and more maintainable. Rasbasts states that "He does not have time for this."   Nor do I. but I have made time because I think it is important for Navigation and Maintenance simplicity. 

You have the changes so use them.

**Comment by rgleason** [comment]
Sorry  I am cranky today. I will stay out of this for awhile.

**Comment by Rasbats** [comment]
@leamas :I was trying to revert to a state previous to where those failed builds were happening. I reverted 230902a I think? This has probably caused the problem. Is it possible to put that commit back into the work again?

Can I just revert the revert?

**Comment by leamas** [comment]
see:  https://github.com/opencpn-manuals/plugins/issues/81#issuecomment-927906654

**Comment by Rasbats** [comment]
Tested the commit 230902a. It fails.

**Comment by leamas** [comment]
Tested locally, or by pushing to build branch. In the latter case: logs?

**Comment by Rasbats** [comment]
Pushed to build branch: [pushing to build branch](pushing to build branch)
There is a lot of junk in main. How to clear this out?

**Comment by Rasbats** [comment]
Sorry ... [https://github.com/opencpn-manuals/plugins/runs/3721489702?check_suite_focus=true](https://github.com/opencpn-manuals/plugins/runs/3721489702?check_suite_focus=true)

**Comment by Rasbats** [comment]
Just an extra plugins directory to remove. I will try pushing to build with that change.

**Comment by Rasbats** [comment]
No ... to do that I need to get build in the same state as main.

**Comment by Rasbats** [comment]
Success. Now push the change to main and build.

**Comment by leamas** [comment]
Another strategy is to first push to build,check the logs, and then push to main...

**Comment by rgleason** [comment]
See, Simplify Maintenance
https://github.com/opencpn-manuals/plugins/issues/72#issuecomment-928504553

**Comment by Rasbats** [comment]
Excellent work by Rick. Yes this is easier to maintain. I LOVE partials! Now to add JavaScript.

**Comment by rgleason** [comment]
Mike I tried making my changes through the Edit this page (I probably shouldnt have) but I hope they work.

https://github.com/opencpn-manuals/plugins/blob/main/manual/plugins/modules/advanced/pages/advanced.adoc

Yes Partials is sweet too..

**Comment by Rasbats** [comment]
>comprized of the partial directory files nav-main.adoc, nav-beta.adoc and nav-all.adoc which are used to construct the left hand navigation bar, which will not be touched in the following edits.

Needs to be:
comprised of the partials directory files nav-main.adoc, nav-beta.adoc and nav-all.adoc which are used to construct the left hand navigation bars, which are edited as necessary.

**Comment by rgleason** [comment]
I made that change, how does the rest of it look?
https://github.com/opencpn-manuals/plugins/blob/main/manual/plugins/modules/advanced/pages/advanced.adoc

How does this get accepted into the document?   Also I don't find a PR anywhere

**Comment by Rasbats** [comment]
Because you are admin your edit is there. No PR needed. Then the same as usual: to test with build, push to main/build.
It won't be in the main manual until Alec does an update, which will pull in your other changes as well.

**Comment by rgleason** [comment]
So should I  (...must I?)

```
git remote update origin
git rebase origin/main
git push origin main:build?

```

Do I have to do this to get the changes included?
or will Alec or someone doing the update, collect these changes automatically and add to main?
