### ISSUE TITLE
sources/ directory cannot sync with sources.state  - symptom is windvane error prevents build

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#81]
So this error was caused by a push changing another plugin in sources.

https://github.com/opencpn-manuals/plugins/actions/runs/1275576816

If this has been done, the next push will surely fail if sources has not been restored.

So why not do that with the xhange in the plugin?  It screws other pushes up!

**Comment by leamas** [comment]
Because it's impossible, the contents of sources/ is not part of the git repo --- that's the very point with it.

**Comment by leamas** [comment]
BTW: Usually these kind of deps are handled using git submodules. However, isomorphic-git, the javascript git implementation which is used by (javascript) Antora does not support submodules.  That's the reason for the source-state.sh script which is extremely rough and without polish, but has the same basic semantics as git submodules.

**Comment by rgleason** [comment]
Ok, I understand that, but when we change the sources file, are things restored in sources-state etc?

It looks like that was done with the push because it complsted and has a green check.

So then I come along, generaly do a rebaae and push and it often fails in windvane.

Why?

**Comment by leamas** [comment]
And please change the heading of this issue, or close it. There is nothing wrong with windvane,  the problem is just that you cannot build since your sources/ directory cannot sync with sources.state. Which is a known problem, as are the work-arounds

**Comment by leamas** [comment]
> So then I come along, generaly do a rebaae and push and it often fails in windvane.

A have no idea why it fails in windvane. You need to learn git basics, to look at the history and possibly checkout  older commits to discover where things went wrong.

Together with the known fact that if _restore_  doesn't work you have  to re-run it after removing either the offending plugin or all plugins  under sources/.

**Comment by rgleason** [comment]
I have looked in history, and I know git. These errors tend to be entirely random as far as I have been able to determine.
This type of error has plagued me from day one with opencpn-manuals/plugins and I had found no real answer to what caused it. 

You advise that it is due to my local sources/ directory cannot sync with sources.state.   I then ask why is my local sources/ directory and sources.state not current with what is in the remote (particularly if I have not touched or changed it)?  Aren't they brought current when I rebase?

I know now that I am going to have to focus on sources as the real issue, which is helpful.

Leamas, pardon me, but if I appear cranky it is because I have back pain and cannot sail during my favorite time after Labor Day.

PS: I really appreciate what you have built here and I understand it is not perfect because you do not have the submodule tools needed to do it well.

**Comment by rgleason** [comment]
I find this statement in the manual now:

> '.gitignore' prevents any local build docs files or sources files being committed to the repository.

This means that every local build when first cloning will have an empty sources directory and must separately execute  _**./sources-state..sh restore**_ to populate that directory.   Also the state will have to be saved back to the **sources-state** file with _**./sources-state..sh save**_ 

This will have to be done on a regular basis because plugin code and documentation gets updated and every time this is done a new commit SHA is needed in **sources-state** file .

The problem I find is that   _**./sources-state..sh restore**_   often fails to complete properly, in fact almost always fails to complete.

**Comment by rgleason** [comment]
Now Rasbats has completely overwritten the work I did to Simplify Navigation.  This is a complete waste of time.

**Comment by leamas** [comment]
Again, and again: if/when it fails: remove either the offending plugin or all plugin under sources, and the run again. You should know this now.

If you want to update the manual, please do.

**Comment by leamas** [comment]
> Now Rasbats has completely overwritten the work I did to Simplify Navigation. This is a complete waste of time.

No, he has reverted it (without explanation, he should have had one). But this is git, it's in the history and  it no problem to resurrect.  You need to discuss med @rasbats why he reverted it and find solutions.

**Comment by rgleason** [comment]
This is not going to be the structure when I get done with this
https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/advanced/advanced.html#_adding_a_new_developer_plugins_manual

I have shown the structure here  Simplify Navigation
https://github.com/opencpn-manuals/plugins/issues/72#issuecomment-927146967

**Comment by leamas** [comment]
@rasbats: If I  understand it correctly , you reverted Rick's commit just because it was still required to edit the same number of files. Correct?

**Comment by rgleason** [comment]
> ..was still required to edit the same number of files. Correct?

What? I don't understand.

**Comment by leamas** [comment]
That was a question to Mike...

**Comment by Rasbats** [comment]
@leamas :I was trying to revert to a state previous to where those failed builds were happening. I reverted 230902a0fa79d856434d05a0b93ba47b069a566b I think? This has probably caused the problem. Is it possible to put that commit back into the work again?

**Comment by Rasbats** [comment]
Can I just revert my revert?

**Comment by leamas** [comment]
Yes.

But you also need more git training ;) In a situation like this, you should not push changes to main. Instead, do the changes locally and push to build. If you had worked this way there would have been no need to revert Rick's changes.

Also, assuming a history like this:
```
37482875 (HEAD -> main) ci: debug junk.
f400056a (origin/main, origin/build, origin/HEAD) sources, site.yml: Use RooiDirk's upstream repo (#23).
d87ca47f update authoring
66bcd01b Revert to 80105f3
7382dae6 [full-linkcheck] empty commit
f2fc7bd9 Revert to 230902a
2c6aa3d7 [full-linkcheck] empty commit
60ab868d Revert "chnge antora back with spell error"
ac6887b8 [full-linkcheck] empty commit
5628d5ed chnge antora back with spell error
8ef75849 Simplify Navigation -sm chngs
d2d7c636 [full-linkcheck] empty commit

```

You can do things like `git push -f origin 7382dae6:build` to investigate if the state at that point was sane.  The next part of the course is about `git bisect`.

**Comment by Rasbats** [comment]
Continuing here: https://github.com/opencpn-manuals/plugins/issues/80

**Comment by rgleason** [comment]
I  like this useful command 
 `git push -f origin 7382dae6:build t`

Have done: 
```
$ git checkout main
$ git reset --hard origin/main
 git log --oneline -10
702141c (HEAD -> main, origin/main, origin/build, origin/HEAD) [full-linkcheck] empty commit
f400056 sources, site.yml: Use RooiDirk's upstream repo (#23).
d87ca47 update authoring
```

Removed all sources folders except .gitkeep
`$ ./source-state.sh restore`
Lots of fatals.
Removed NmeaConverter_pi from sources
`$ ./source-state.sh restore NmeaConverter_pi`

> Restoring into NmeaConverter_pi
> Cloning into 'NmeaConverter_pi'...
> remote: Enumerating objects: 36, done.
> remote: Counting objects: 100% (36/36), done.
> remote: Compressing objects: 100% (25/25), done.
> remote: Total 36 (delta 0), reused 26 (delta 0), pack-reused 0
> Receiving objects: 100% (36/36), 8.36 KiB | 1.39 MiB/s, done.
> remote: Enumerating objects: 17, done.
> remote: Counting objects: 100% (17/17), done.
> remote: Compressing objects: 100% (16/16), done.
> Receiving objects:  58% (10/17)sed 11 (delta 1), pack-reused 0Receiving objects:  52% (9/17)
> Receiving objects: 100% (17/17), 170.13 KiB | 487.00 KiB/s, done.
> Resolving deltas: 100% (1/1), done.
> Updating files: 100% (17/17), done.
> remote: Enumerating objects: 34, done.
> remote: Counting objects: 100% (34/34), done.
> remote: Compressing objects: 100% (32/32), done.
> remote: Total 34 (delta 3), reused 23 (delta 1), pack-reused 0Receiving objects:  97% (33/34), 1.05 Receiving objects: 100% (34/34), 1.27 MiB | 712.00 KiB/s, d
> one.
> Resolving deltas: 100% (3/3), done.
> Updating files: 100% (51/51), done.
> fatal: invalid refspec '48fa9a5f6b1d0edb2e9a951c13700e45a596e2c1?'
> error: pathspec 'FETCH_HEAD' did not match any file(s) known to git

Do the final Fatal and error indicate some failure in cloning NmeaConverter?
This happens with any number of plugins.   Do I have a bad internet connection or something?

**Comment by leamas** [comment]
No, if it fails after removing everything under sources/ you have a bad sources.state.

**Comment by rgleason** [comment]
In fairness to Rasbats  the last 3 were mine, trying to get it to complete.

```
5628d5ed chnge antora back with spell error
8ef75849 Simplify Navigation -sm chngs
d2d7c636 [full-linkcheck] empty commit

```

**Comment by rgleason** [comment]
>No, if it fails after removing everything under sources/ you have a bad sources.state.

Ok, what should I do?  
Run   
`./source-state.sh update   .
`
which updates one or all directories in sources/ folders with the distributed plugins "manual"

That seemed to work with comments noting where HEAD was.
Then 
`./source-state.sh restore   .
`
All FATALS

**Comment by rgleason** [comment]
This worked before and built properly  Now that Rasbats has pushed it again, it does not work.
[Simplify Navigation OpenCPN Plugins Manual #441](https://github.com/opencpn-manuals/plugins/actions/runs/1278657820)

Also my original git push origin main:main  oof  Simplify Navigation is gone.  I can't find it.
But I find it here  https://github.com/opencpn-manuals/plugins/actions/runs/1271870615
Successfully built and the the html from the build branch worked fine.

**Comment by Rasbats** [comment]
> my original git push origin main:main oof Simplify Navigation is gone

If you test this commit with `git push -f origin 230902a:build` I think you will find that commit did not build and resulted in the errors that followed. We are now back in a position where you can test your simplification again by pushing changes to build.

**Comment by Rasbats** [comment]
Something I use where I need to use old work ... browse files of a commit and download the zip. Use the files from the zip to update the work.

**Comment by rgleason** [comment]
> If you test this commit with git push -f origin 230902a:build I think you will find that commit did not build and resulted in the errors that followed.


WRONG   It built here successfully, as I said above

But I find it here https://github.com/opencpn-manuals/plugins/actions/runs/1271870615

230902a0fa79d856434d05a0b93ba47b069a566b

**Comment by Rasbats** [comment]
>WRONG It built here successfully

Was this when you pushed it to origin build?

**Comment by leamas** [comment]
> Something I use where I need to use old work ... browse files of a commit and download the zip. Use the files from the zip to update the work.

That's a really convoluted way to do it... You can just checkout the commit locally. For example, `git checkout 5628d5ed` will bring the tree to the state of that commit. `git checkout main` takes you back to the beginning. 

There is no need to checkout the while tree. `git checkout HEAD^^ site.yml` will checkout site.yml as of the grandfather of current HEAD

Furthermore, you use `git diff` to compare different version, `git bisect`to find the  commit causing an error, ...

**Comment by Rasbats** [comment]
@leamas :)

**Comment by leamas** [comment]
> Was this when you pushed it to origin build


No, when he pushed to build.  Logs [here](https://github.com/opencpn-manuals/plugins/runs/3705946990), you see the commit as last line of the Checkout section. Builds fine.

**Comment by rgleason** [comment]
Just got the hang of ./source-state.sh

1. Use  ./source-state.sh restore,  if there are Fatal or Errors delete the recent changed plugin (or all, ..leaving .gitkeep) and try rerunning restore.  (deleting all plugin folders in sources is about 200mb so best to have fast internet)
2. If it still fails, the sources-state file is bad, so run  ./source-state.sh update  to align sources folders current plugin commits
3. If those all complete without error, then bring the sources-state file current with  ./source-state.sh save
4. Then if you run  ./source-state.sh restore it should complete nicely.

**Comment by Rasbats** [comment]
This is the one I was looking at:[https://github.com/opencpn-manuals/plugins/runs/3714490697?check_suite_focus=true](https://github.com/opencpn-manuals/plugins/runs/3714490697?check_suite_focus=true)

**Comment by leamas** [comment]
> If it still fails, the sources-state file is bad, so run ./source-state.sh update to align sources folders current plugin commits

Or check out it from a working commit, depending on what you want.

**Comment by rgleason** [comment]
Have made notes about this here
https://github.com/opencpn-manuals/main/discussions/20

Closing
