### ISSUE TITLE
Why are the CI scripts necessary under "sources"?

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#83]
OM-plugins\sources\watchdog_pi\**ci**    <---- Why is this necessary?  CI is there for all plugins under Sources!

**Comment by Rasbats** [comment]
`git sparse-checkout set manual antora.yml modules ci`
In _source-state.sh_
Alec will tell you why ci is included. I cannot see the need for it. But ...

**Comment by rgleason** [comment]
NOTE:  I am not talking about   the CI HERE!!!

├───ci
│       build-and-deploy.sh
│       dokuwiki-links.sh
│       linkchecker.sh
│       unresolved-xrefs.sh
│       w3c-linkcheck.sh

I am talking about the ci found in **sources\plugin_name_pi\CI**
It is useless for documents.

**Comment by rgleason** [comment]
**Example**

```
OM-plugins\sources\watchdog_pi\ci
   circleci-build-android-arm64.sh
   circleci-build-android-armhf.sh
etc   

```

The entire CI directory is like this and unnecessary.
All the other plugins have the same CI directory.

**Comment by rgleason** [comment]
Never got an answer to this. Still know it is unnecessary, but closing it anyway

**Comment by rgleason** [comment]
#
