### ISSUE TITLE
Add an overall chapter on installing and uninstalling plugins

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/plugins#9]
The current [dokuwiki docs](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:install_and_enable) contains some general info on plugins, how to install/uninstall etc. We probably need to include or refer to this somehow. 

For now,  linking to the dokuwiki page. It's in the user manual, so it's out of scope for current work anyway. 

EDIT: OTOH, the plugin manual *is*  user-facing.  Perhaps it would make sense to copy the current dokuwiki chapter into here. Or, perhaps not.

**Comment by rgleason** [comment]
Rewrite  Install & Uninstall
If you change this to a document in asciidoc, you will need to change the link in many plugins.

Also As plugins documentation goes on line as asciidoc, the links to other plugins is going to have to be updated.

**Comment by leamas** [comment]
Fixed in dadf9e6. Closing

**Comment by leamas** [comment]
> Also As plugins documentation goes on line as asciidoc, the links to other plugins is going to have to be updated.

Not really. Proper cross-plugin references done using xref:  will work after a simple rebuild
