### ISSUE TITLE
o-chart_pi  page needed now

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#91]
Similar to 
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn%3Aopencpn_user_manual%3Aplugins%3Acharts%3Aocharts&lng=en

will also add to Bdbcat rpos

**Comment by o-charts** [comment]
done by https://github.com/opencpn-manuals/o-charts_pi/pull/1

**Comment by rgleason** [comment]
Thanks
